### ISSUE TITLE
Create / Edit management actions

### ISSUE THREAD

**Issue by bartaelterman** [inbo/vespa-watch#10]
Create a form for creating/editing management actions. Only authenticated users can do this

**Comment by niconoe** [comment]
Just to clarify: this is about creating / editing the occurrence of a management action(for example add a comment about a given nest destruction ), not the management action type itself (for example add a new kind of management action in the admin interface - I guess this will be rather static)?

If so I think the first form we'll need is a single one for firefighters to create both an occurrence and a management action (those two would be distinct models/database tables)

**Comment by bartaelterman** [comment]
Indeed, it's for the firefighters to record the fact that a management action has been performed.
 
I created three separate tickets:
- #8 authenticated user can create an observation
- This one
- #11 create the observation inline (or together in one form) with the management action
- #9 guest user can create an observation (probably milestone 2)

I thought it would be easy to simply start with just the two forms separately (so #8 and this one). I guess that even for the combined form, you will use two separate django form objects or not? If you think there is little use in doing the two forms separated first, feel free to close this issue and tackle #11 right away.
