### ISSUE TITLE
Add * to indicate all mandatory fields

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#103]
Mandatory fields should be indicated as such with a `*` on the form. This is currently not the case for `Latitude`, `Longitude`, `Terms of service`.

**Comment by peterdesmet** [comment]
See #207

**Comment by peterdesmet** [comment]
To be tested again.

**Comment by peterdesmet** [comment]
For nest, * still missing on:

- First name, last name (but see #220)

For individual, * still missing on:

- Lat
- Long
- Address

**Comment by bartaelterman** [comment]
Since there is issue #134 now, this issue is obsolete.
