### ISSUE TITLE
Map design

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#106]
Homepage map:

- Nest: bigger circles + blue
- Individual: smaller circles + orange

Management map (only nests):

- Outcome = finished: green
- Outcome = unfinished: red

What management outcomes are considered finished should be defined by @KarelSchoonvaere.

**Comment by bartaelterman** [comment]
I added [a property `finished`](https://github.com/inbo/vespa-watch/blob/master/vespawatch/models.py#L563) based on the value of the management action. We can always change it (and we should once #107 is closed)

Colors can be updated in the settings file: https://github.com/inbo/vespa-watch/blob/master/djangoproject/settings/base.py#L183. Reassigning this ticket to @peterdesmet to tackle the design label.

**Comment by peterdesmet** [comment]
Is ok for homepage, moving to milestone 2 for management form.

**Comment by peterdesmet** [comment]
There will be no map on the management page. Closing issue.
