### ISSUE TITLE
Management outcomes

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#107]
@KarelSchoonvaere, can you redefine the management outcomes + which ones are considered "in progress" (red) and which ones considered "done"? The current dropdown is:

- Full destruction, no debris
- Partial destruction/debris left
- Empty nest, nothing done

But you are welcome to add/remove actions (in conversation with the firefighters).

**Comment by peterdesmet** [comment]
The action pending is an intermediate stage that we will not use. The dropdown should therefore be:

```
professional permas-D treatment
classic permas-D treatment
complete manual removal
partial manual removal
not treated
unknown
```

**Comment by bartaelterman** [comment]
We currently have:

- Full destruction, no debris
- Partial destruction/debris left
- Empty nest, nothing done
- Unknown

1. I'll add `professional permas-D treatment` and `classic permas-D treatment` 
2. For the other values, note that they have different values in the database: `FD`, `PD`, `ND`, `UK`. It's easy enough to change the translations for these values. But the result would be that the values in the database show no logical link to the text anymore (e.g. `complete manual removal` will remain encoded in the database as `FD`) . Changing the actual values requires a data migration. It seems difficult for django to do this correct without any manual intervention (it can see that the values for the field are _changed_ but it's not easy to properly deduce which old value changed into which new value). For this, I'd at least like to be able to discuss it with @niconoe, if needed.

. and changing the translations for the 4 existing?

**Comment by bartaelterman** [comment]
There are currently no management actions in production. Let's go for the migration option.

**Comment by peterdesmet** [comment]
I still see the old controlled vocab. It should be updated soon (before we _have_ management actions):

```
PERMAS_D_PROF / professional permas-D treatment
PERMAS_D_CLASSIC / classic permas-D treatment
REMOVAL_COMPLETE / complete manual removal
REMOVAL_PARTIAL / partial manual removal
NOT_TREATED / not treated
UNKNOWN / unknown
```

**Comment by peterdesmet** [comment]
See https://github.com/inbo/vespa-watch/issues/361

**Comment by niconoe** [comment]
@peterdesmet or @KarelSchoonvaere:

I'm finally implementing this :) 

Can I get a Dutch translation for the different values (professional permas-D treatment / classic permas-D treatment / complete manual removal / partial manual removal / not treated / unknown)? bedankt!

**Comment by peterdesmet** [comment]
value | English | Dutch
--- | --- | ---
PERMAS_D_PROF | professional Permas-D treatment | professionele Permas-D behandeling
PERMAS_D_CLASSIC | classic Permas-D treatment | gewone Permas-D behandeling
REMOVAL_COMPLETE | complete manual removal | volledige manuele verwijdering
REMOVAL_PARTIAL | partial manual removal | gedeeltelijke manuele verwijdering
NOT_TREATED | not treated | niet behandeld
UNKNOWN | unknown | ongekend

@niconoe I think you can implement them as above. @KarelSchoonvaere or @timadriaens let me know if you want to change the Dutch translations

**Comment by niconoe** [comment]
This is now implemented and visible in the [UAT environment](https://uat.vespawatch.be/).
