### ISSUE TITLE
Restructure templates

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#111]
As discussed on 22 Nov, structure the templates as such:

- [ ] `action_create.html`: delete, replaced by `includes/managementaction_modal.html`
- [ ] `action_update.html`: delete, replaced by `includes/managementaction_modal.html`
- [x] `base.html`: keep
- [x] `index.html`: keep
- [x] `individual_confirm_delete.html`: keep, but could become modal
- [ ] `individual_create.html`: add
- [x] `individual_detail.html`: keep
- [x] `individual_form.html`: move to `includes/individual_form.html`
- [x] `individual_update.html`: add (or is this the same as `individual_create.html`?)
- [x] `management.html`: keep
- [ ] `managementaction_confirm_delete.html`: delete, will be handled by `includes/managementaction_modal.html`
- [ ] `includes/managementaction_modal.html`: add
- [x] `nest_confirm_delete.html`: keep, but could become modal
- [ ] `nest_create.html`: add
- [x] `nest_detail.html`: keep
- [x] `nest_form.html`: move to `includes/nest_form.html`
- [x] `nest_update.html`: add (or is this the same as `nest_create.html`?)
- [x] `new_observation.html`: remove
- [x] `observation_create.html`: remove
- [x] `observation_update.html`: remove
- [x] `terms_of_service_modal.html`: move to `includes/terms_of_service_modal.html`

Flow between pages:

![img_7605](https://user-images.githubusercontent.com/600993/48950489-97947d00-ef3b-11e8-835d-1a49355a7382.jpg)

**Comment by bartaelterman** [comment]
I (re)moved some templates: 0c8e8972211dae193753da2b3ce3087938e5c7c6
The management modal will be tackled in #101
