### ISSUE TITLE
Allow position to be recorded from mobile phone

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#112]
When using vespawatch in the field, it would be good if the website can use the position of the user and use that as default location for recording a new observation. @niconoe @bartaelterman have done this before?

**Comment by bartaelterman** [comment]
I haven't done it before. However it looks like these days, there is a [HTML5 Geolocation API](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API) that should make this easy and well supported on most browsers.

**Comment by niconoe** [comment]
There's now a basic autodetection based on the HTML5 Geolocation API.

As mentioned in various other tickets, those position/map widgets should be more polished (code, visual and interactions).
