### ISSUE TITLE
Minify our custom Javascript with npm

### ISSUE THREAD

**Issue by niconoe** [inbo/vespa-watch#116]
Among other things, it will make it obvious when we're by accident editing the file in `static` instead of the one in `static_src`

**Comment by peterdesmet** [comment]
How would you minify both files (vespawatch & language selector) into one?

**Comment by niconoe** [comment]
For now I just merged vespawatch & language selector at the source level. So one source -> one minified.

It was the simplest solution and it didn't really made any sense to keep the language selector apart, given all the rest was bundled together in a large JS file. At a later stage, splitting our source into multiple files might be worth exploring, but we might end up with Webpack and stuff, so I'll delay it just like #97.
