### ISSUE TITLE
Editing a nest (probably also an individual) via the forms lose inaturalist_id

### ISSUE THREAD

**Issue by niconoe** [inbo/vespa-watch#117]
Thus breaking the sync_process.

TODO: Once it's solved, check that the mechanism that prevents the species to be changed on pushed observations still works.

**Comment by niconoe** [comment]
@bartaelterman : is there a reason that `inaturalist_id` is listed in the "fields" attributes of the form? I was wondering if the fact it's specified in the form but not the template was responsible for this data loss bug? AFAIK inaturalist_id should be viewable, but not changeable (except in the admin for debugging and manually solving sync issues).

**Comment by bartaelterman** [comment]
Or maybe just remove it from the form? It's not editable and so far, it is only viewable in map pop up.

**Comment by niconoe** [comment]
Yes, that was the plan, I just wanted to unsure there was not a good reason I was overlooking. 

Just did it, it seems to work!
