### ISSUE TITLE
Extract hard coded configuration variables from vespawatch.js

### ISSUE THREAD

**Issue by niconoe** [inbo/vespa-watch#122]
(API calls for example)

Put our JS config in a global object `VWConfig` created in templates?

**Comment by niconoe** [comment]
Another possible approach: define Vue templates in a specific Django template (using `<script type="text/x-template"`), that we include in "real page templates". That way, the Django url template tag can be used.

**Comment by bartaelterman** [comment]
Definitely.
I'm not sure what you mean with that latter option. But I like the simplicity of _Solution #1_  in [this blogpost](https://codeburst.io/how-to-call-api-in-a-smart-way-2ca572c6fe86)

**Comment by niconoe** [comment]
@bartaelterman: I just implemented a mechanism to extract configuration (URLs and others) from the JS file and move it to the Django side (so URLs can be automatically generated, for example).

It works like this:

- In JavaScript, find the config in a global `VWConfig` object
- On the Django side, populate this object in `templatetags/custom_tags.py` (`js_config_object()`). For some things, it's probably to import from the Django settings there (see `fill_opacity`for example)

There are still hard coded values in vespawatch.js that should be properly extracted.

**Comment by niconoe** [comment]
I think we're good for now.
