### ISSUE TITLE
Remove generated files from source control

### ISSUE THREAD

**Issue by niconoe** [inbo/vespa-watch#123]
For example `vespawatch.min.js`, CSS, ...

Prerequisites:

- [x] Add instructions to generate them (dev. environment)
- [x] Automate this for production

**Comment by stijnvanhoey** [comment]
For the record:

- described in readme for local development
https://github.com/inbo/vespa-watch#generate-static-files
- included in the deployment:
https://github.com/inbo/vespa-watch/blob/73a9856fdbcef6e534ebb0c24f5fbb85b062f70f/.ebextensions/01_python.config#L56-L57
- ignored in repo:
https://github.com/inbo/vespa-watch/blob/73a9856fdbcef6e534ebb0c24f5fbb85b062f70f/.gitignore#L130

closing.
