### ISSUE TITLE
Can we attach actions to observations coming from iNat?

### ISSUE THREAD

**Issue by niconoe** [inbo/vespa-watch#126]
... If so, we'll have to update the sync process, since all iNat observations are dropped/recreated on each `pull` operation (the actions would then be lost).

**Comment by niconoe** [comment]
Yes, we'll need a proper update mechanism for this. Then, those observations are not visible anymore from the public pages but only from the admin.

**Comment by peterdesmet** [comment]
Yes we can, because we decided in #2 that no observation can be automatically deleted.
