### ISSUE TITLE
App offline during sync_pull?

### ISSUE THREAD

**Issue by niconoe** [inbo/vespa-watch#128]
Inconsistent/incomplete data can appear otherwise (for example, after deleting and before re-importing the observations coming from iNaturalist).

**Comment by stijnvanhoey** [comment]
As in, it will be required to have the app offline? Or can we still make it work?

**Comment by peterdesmet** [comment]
@niconoe can you explain in more detail. Are you worried what happens if the app goes offline on a sync_pull?

**Comment by niconoe** [comment]
Nope, I was just wondering if it wouldn't be safer to put the website temporarily offline during the `sync_pull` process, to avoid:

- showing incomplete/incorrect information to users (for example, the observations originating in iNaturalist are all dropped at the beginning of the pull process, are recreated one by one afterwards - the process takes a couple of minutes)
- race conditions: what happen if the same obs is modified at the same time by an user and the sync process.

I think it may be difficult to take a final decision now, the devil being in the details. Some influencing factors:

- Duration of the sync_pull process
- Frequency of the sync_pull process
- Do we continue with the "drop everything at first - recreate one by one" logic for iNat observations (we may need to do something smarter because of #126)

**Comment by peterdesmet** [comment]
The two reasons listed by @niconoe won't happen, because we decided in #2 that obs are not dropped + can not be edited.

Let's not put the app offline during sync, unless we encounter issues.
