### ISSUE TITLE
Observation show/edit: clearly show origin/sync status

### ISSUE THREAD

**Issue by niconoe** [inbo/vespa-watch#130]
Currently the origin (iNat Vs VespaWatch) and sync status is not shown (at least directly/clearly) to the user, which can make things confusing. 

We could use a Bootstrap badge (or similar) to improve this.

**Comment by peterdesmet** [comment]
Good idea!

**Comment by peterdesmet** [comment]
Would maybe good to replace/combine this with the `inat_vv_confirmed` status (#139)

**Comment by peterdesmet** [comment]
Obs now show if they are synchronized with iNat and confirmed.
