### ISSUE TITLE
vespawatch_individual.taxon_id does not exist

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#131]
I can run the webserver, but browsing I get what I believe is an API error:

```
django.db.utils.ProgrammingError: column vespawatch_individual.taxon_id does not exist
LINE 1: ...espawatch_individual"."originates_in_vespawatch", "vespawatc...
```

Any suggestion to solve this?

**Comment by niconoe** [comment]
If you haven't use the app after December 3, you should drop/recreate the database then run `python manage.py migrate`.

Otherwise, just run `python manage.py migrate`. Keep us informed!

**Comment by peterdesmet** [comment]
Dropped database, now fixed.
