### ISSUE TITLE
Images are not deleted when observations are

### ISSUE THREAD

**Issue by niconoe** [inbo/vespa-watch#132]
... At least for observations from iNaturalist, needs further investigation.

**Comment by peterdesmet** [comment]
@niconoe is this still the case?

**Comment by bartaelterman** [comment]
If so, as of [the dropzone PR](https://github.com/inbo/vespa-watch/pull/310) there is now a management command to remove orphan images so I wouldn't bother about this.

**Comment by bartaelterman** [comment]
I tested this (via the admin interface) and the images are properly deleted. Closing this issue.
