### ISSUE TITLE
Mandatory/non-mandatory fields on obs form

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#134]
Field that should be mandatory are indicated with *.

## Nest

field | mandatory status | * indicated
--- | --- | ---
**Species*** | ok | ok, is prepopulated
**Photo*** | make mandatory: solved | ok
**Coordinates*** | ok | ok
**Location address*** | make mandatory: solved | ok
**Date*** | ok | ok
**Nest height*** | make mandatory: solved | indicate
Nest size | ok | ok
Comments | ok | ok
**Observer name*** | make single field, make mandatory: solved | indicate: solved
**Telephone*** | ok | indicate: solved
**Email*** | ok | indicate: solved
**I agree with privacy policy*** | ok | indicate: solved

## Individual

field | mandatory status | * indicated
--- | --- | ---
**Species*** | ok | ok, is prepopulated
**Photo*** | make mandatory: solved | ok
**Coordinates*** | make mandatory: solved | indicate: solved
Location address | ok | ok
**Date*** | ok | ok
Individual count | ok | ok
Behaviour | ok | ok
Comments | ok | ok
Observer name | make single field, not mandatory: solved | ok
Telephone | ok | ok
**Email*** | make mandatory: solved | indicate: solved
**I agree with privacy policy*** | ok | indicate: solved

**Comment by peterdesmet** [comment]
@niconoe, can you:

- Remove `observer_is_beekeeper`?
- Update `observer_first_name`, `observer_last_name` to `observer_name`?

**Comment by peterdesmet** [comment]
@bartaelterman see issue body: can you set the appropriate fields to mandatory? Not sure whether it is better to do this in `forms.py` or `models.py`, but it can be as default as possible (no custom error messages)

**Comment by peterdesmet** [comment]
@KarelSchoonvaere I don't remember: does the fire station need the address of the user reporting and/or the address where the nest is located?

**Comment by bartaelterman** [comment]
I'll try to change it in the model. In theory, that's the right place. Those form validation messages are the default django ones. I would have to figure out how to customise them. Do you really want that?

**Comment by peterdesmet** [comment]
No, no need to customize: I want the default error messages.

**Comment by bartaelterman** [comment]
@peterdesmet I'll wait for Karel's input on this one. Is there also a list like this for Individuals? If the field is required for both, I can indicate it on the model. If it is only required for a nest, I have to indicate that on the form.

**Comment by peterdesmet** [comment]
Reviewed with @KarelSchoonvaere, this can be tackled now. I'll create separate issues for the field changes.

**Comment by KarelSchoonvaere** [comment]
@peterdesmet voor nest meldingen is het belangrijkste dat de melder kan gecontacteerd worden door het aangewezen team van de brandweer en dat de exacte locatie of adres van het nest al is doorgegeven. Het adres van de melder is irrelevant. In vele gevallen zal dit niet overeenkomen met de locatie van het nest.

**Nest**
- Locatie adres wordt automatisch ingevuld op basis van de coordinaten, deze flow zit goed. Dan nog de melder de mogelijkheid geven om het adres aan te passen indien nodig is prima. Dit adres komt overeen met wat het wespenteam in hun GPS steekt voor de interventie. Mandatory houden dus, samen met de hele locatie tab. 
- hoogte is belangrijk voor beslissing brandweer om een inschatting te maken welke verdelgingsmethode toe te passen, meerbepaad methode manueel (onder 4m) of methode telescoopstok (boven 4m) te kiezen. Dus mandatory
- Breedte van het nest kan in vele gevallen ingeschat worden door combinatie foto, ervaring en tijdstip in het jaar. In sommige gevallen zal het nest niet zichtbaar zijn (bvb spouwmuur), en dan is dit veld een obstakel. Dus best niet mandatory.
- Het brandweer team moet de mogelijkheid hebben om de melder te contacteren. Telefoonnummer en emailadres mandatory houden.
- velden Photo, Date, Observer name, Policy agreement moeten mandatory blijven. 

Individual
- Location address is hier niet relevant want de melding wordt NIET gekoppeld aan een brandweerinterventie. Coordinaten zijn wel noodzakelijk voor  goede registratie. 
- Email adress mandatory houden. In het ideale geval dat iemand in de toekomst wordt betaald voor AH beheer dan worden melders aangemoedigd om het nest te zoeken. Dit verhoogt de vindkansen enorm, maar vraagt opvolging. Default valt deze opvolging na juni 2019 weg, maar mijn inziens moet de mogelijkheid blijven bestaan. Het leeuwendeel van de persoonlijke contacten verliep via email. Dus verkies dit veld boven telefoon. 
- Observer name en Telephone mag je behouden, maar zijn op zich niet zo belangrijk als email adres. Observer name zeker behouden zodat melder met de naam kan aangesproken worden in emails.
- andere velden zijn goed zoals ze zijn.

**Comment by KarelSchoonvaere** [comment]
Huidig wordt de melder beperkt om maar 2 foto's op te laden. Waarom is dit? Bij voorkeur zijn het aantal foto's ongelimiteerd

**Comment by KarelSchoonvaere** [comment]
Schrijffout in meldingsformulier individu Aziatische hoornaar: 
veld "Aantal individuën", individuen zonder trema

**Comment by KarelSchoonvaere** [comment]
In meldingsformulier individu AH staan de veldopties voor het veld "Gedrag" nog Engelstalig.

**Comment by KarelSchoonvaere** [comment]
In het meldingsformulier nesten AH moet je foto's opnieuw uploaden na een foutmelding (mandatory field niet ingevuld). Kan dit ingesteld worden dat de eerder geselecteerde foto's in het formulier blijven?

**Comment by KarelSchoonvaere** [comment]
When reporting an individual there's a problem with finding a query address.
When I neglect "Decteer huidige positie" but fill in "Zomergem" and click on "Zoek". Than the coordinates and pin on the chart are set to my current position and not to the coordinates of Zomergem. When I click "Zoek" a second time, then the coordinates of Zomergem are found and the pin is pointed at the correct location. 
When I first click "Decteer huidige positie" and after fill in "Zomergem" and click on "Zoek", it also works perfect. 

Seems to me the address look-up only works after the user's current position is known.

**Comment by peterdesmet** [comment]
@KarelSchoonvaere I'm addressing your comments in separate issues

Typo individuals fixed in df1ab4a
Values for dropdown fixed in 4329d31
Re-upload foto's: reported as #252
Position detection: added to #169

**Comment by peterdesmet** [comment]
@niconoe, this issue has the highest priority imo.

**Comment by bartaelterman** [comment]
@niconoe I've added a couple of commits. The current state:

- Required fields are required.
- Required fields are indicated as required.
- Form validation fails when a required field is not set.

Note:
- I've split the forms of Individual and Nest. Both now have a default form, and an Unauthenticated version of the form that requires some details about the observer and is rendered when the user is not logged in.
- I've added the validation of the image as a form wide validation error (not attached to a specific field, because the form itself doesn't really have an images field). The validation message doesn't look pretty
- I haven't merged observer first name and last name yet
- Form error messages are not always pretty (wasn't there a separate ticket for that?)
- Form fields that fail the validation are not rendered consistently (the fields that are part of a Vue component are not rendered the same way a default django form field is rendered: red with a little cross and a failure message below it). Also, the failure messages below (default) form fields are shown twice
- There seems to be a lot of translation work: field names, error messages, ...

**Comment by niconoe** [comment]
Just merged master so we have:

- the first name / last name merge
- the removal of observation_is_beekeeper
- all recent changes in other parts of the application

**Comment by stijnvanhoey** [comment]
Another side effect that will be solved by  mandatory fields:

```
ERROR 2019-05-22 11:26:01,462 log 3776 140644132747008 Internal Server Error: /obs/individual/add/
Traceback (most recent call last):
File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
response = get_response(request)
File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
response = self.process_exception_by_middleware(e, request)
File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/opt/python/current/app/vespawatch/views.py", line 106, in create_individual
if form.is_valid():
File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/forms/forms.py", line 185, in is_valid
return self.is_bound and not self.errors
File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/forms/forms.py", line 180, in errors
self.full_clean()
File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/forms/forms.py", line 381, in full_clean
self._clean_fields()
File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/forms/forms.py", line 399, in _clean_fields
value = field.clean(value)
File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/forms/fields.py", line 147, in clean
value = self.to_python(value)
File "/opt/python/current/app/vespawatch/fields.py", line 22, in to_python
value = value.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
```
would be good to check this when updating the code...

**Comment by peterdesmet** [comment]
Confirmed that all changes are implemented.
