### ISSUE TITLE
Fields for management action form

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#137]
- [x] **Action** (mandatory) (instead of `Outcome`)
- [x] ~~**Person name**~~: remove, assumed to be zone
- [x] **Start time** (mandatory) (instead of `Action time`): includes date
- [ ] **End time** (mandatory): assumed to be same date, so don't ask date again
- [x] ~~**Duration**~~: remove
- [x] **Number of persons** (mandatory): integer
- [ ] **Materials used** (mandatory): multiple select, e.g. `ladder wagen`
- [ ] **Photo(s)** (optional): not sure if we need to support more than one photo
- [x] **Comments** (optional)

Form should work on a smartphone!

**Comment by peterdesmet** [comment]
Needs to be tested.

**Comment by bartaelterman** [comment]
The current management action form contains the following fields:
- action
- start time
- duration
- person

as discussed, I'll also add the use account.

Are the other fields described at the beginning of this issue still needed?

**Comment by peterdesmet** [comment]
I don't recall why we opted for starttime/endtime rather than starttime/duration, but wouldn't it be easier (for the form) to implement with two date fields? I don't know.

A comments field would still be useful.

**Comment by peterdesmet** [comment]
Photos + material used doesn't seem to necessary, but number of persons is useful to calculate effort.
