### ISSUE TITLE
Dropdown list for action (types)

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#138]
1. `Nestverdelging`
2. `Nestverdelging: opvolging reeds behandeld nest`
3. `Geen actie: geen Aziatische hoornaar`
4. `Geen actie: dubbele melding nest`
5. `Geen actie: andere reden`

@KarelSchoonvaere can you review these choices?

- For 1. do you still want to make the distinction between `full/partial`, `debris/no debris`? **conclusion: no**
- For 2. do you want this? Because of the one-one relationship, they would have to log the nest again. **conclusion: yes, keep this category. There will be no actual link between duplicates**
- We discussed making the other fields gray for `Geen actie`. That is the easiest solution, but 1) I would always leave the option for adding images + comments. That would mean that no date can be recorded. I think that is fine. **conclusion: yes, leave option open**

**Comment by Erytran** [comment]
5 points are good. For 1 you can leaf out full/partial or debris/no debris options. Let's keep it straightforward. Besides, the manual removing strategy has been lifted from the SOP, so technically speaking nests will never be removed during eradication actions. 
For 2. as we discussed in the meeting, re-activity in a previously eradicated nest will be reported by a new nest. The firefighters should have to option to merge two reports of the same nest. 
Ok for adding images.

**Comment by peterdesmet** [comment]
> For 2. as we discussed in the meeting, re-activity in a previously eradicated nest will be reported by a new nest

**agreed**

> The firefighters should have to option to merge two reports of the same nest.

**as I understood, without making an actual link, but just a dropdown option**

Example 1:

1. Nest is reported (A)
2. Firefighters contact reporter, take action and report as `Nestverdelging` for (A)
3. Nest is reported (B)
4. Firefighters contact reporter, learn this is a case of re-activity in a previously eradicated nest, take action and report as `Nestverdelging: opvolging reeds behandeld nest` for (B)

Example 2:

1. Nest is reported (C)
2. Firefighters contact reporter, take action and report as `Nestverdelging` for (C)
3. Nest is reported (D) (can even happen before step 2)
4. Firefighters realize this is a duplicate report of nest (C) and report as `Geen actie: dubbele melding nest`

Note that in the two examples, no actual link is made between (A) and (B) or (C) and (D): (B) and (D) are just marked in a way that allows to know these are duplicates. @Erytran should there be an interface to indicate **of which nest** (B) or (D) where a duplicate?

**Comment by KarelSchoonvaere** [comment]
OK for no actual link. 
There will always be the case of redundant reports, as is now in waarnemingen.be

@Tim, I am thinkin of your reports to Europe. How will you deal with redundant reports in your statistics?

**Comment by timadriaens** [comment]
based on the categories (reeds behandeld, dubbele melding...), we can filter out the doubles. If that does not work --> based on coordinates, dates etc. i.e. manual filtering

**Comment by peterdesmet** [comment]
Superseded by #107
