### ISSUE TITLE
Only show validated nests to fire brigade

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#139]
Any recorded nest should be validated as being `Vespa velutina` by the iNaturalist community **before** it is shown as a nest that requires action by the fire brigade. Even though we do not require that information for individuals, it would be good to record that there as well (so we might filter on it).

1. Set `inat_vv_confirmed = TRUE` for:

```yaml
community_taxon_id: 119019
community_taxon_id: 560197 # ssp. nigrothorax
```

2. Set `inat_vv_confirmed = NULL` for:

```yaml
community_taxon_id = null # not yet validated
```

3. Set `inat_vv_confirmed = FALSE` for any other value of `community_taxon_id`

**Comment by niconoe** [comment]
Should be tackled when revamping the sync process (currently planned: "as late as possible, but before 0.1").

**Comment by peterdesmet** [comment]
Can be kept for milestone 2.

**Comment by niconoe** [comment]
Status:

- [x] creating an `inat_vv_field` at the model level (done in the `new_sync` branch)
- [ ] make sure that flag is properly set by the synchronization script (will be done in the `new_sync` branch)
- [ ] show validated nests to fire brigade: for milestone 2

**Comment by bartaelterman** [comment]
Implemented on [`management`](https://github.com/inbo/vespa-watch/tree/management) branch.

@niconoe I think the second point from your previous comment is also implemented, right?

**Comment by peterdesmet** [comment]
Yes, this has been done. Closing issue.
