### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by bartaelterman** [inbo/vespa-watch#14]
Our app should support internationalization. The first language to support is dutch, but we should be able to roll out french and english versions too.

This will likely come with some kind of interface where administrators can translate keys.

**Comment by niconoe** [comment]
Will use standard Django features for that. 

Ok for everyone if the strings in the HTML templates are in English (then translated to dutch via po/mo files before being shown to the user) so the code base stays english (same things for the variable name, for example) while the UI is (at first) forced to Dutch for visitors?

**Comment by stijnvanhoey** [comment]
make sure this is already working for the warnings/errors

**Comment by niconoe** [comment]
I just added a first version of the `.po` files so you can start filling them.

It might be good that you have at least a quick look at [the relevant page on Django's documentation](https://docs.djangoproject.com/en/2.1/topics/i18n/translation/), but in a nutshell:

- After filling the Dutch strings in the `.po` files, you must compile them to the more efficient `.mo` file format with: `python manage.py compilemessages`.
- After updating the app with new or changed strings, run `python manage.py makemessages -l nl` and `python manage.py makemessages -d djangojs -l nl` (for JS) to update the `.po` files.

**Comment by peterdesmet** [comment]
Tested and this works, for both `{% trans %}` and javascript. Closing issue.
