### ISSUE TITLE
Species to present to user

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#144]
@KarelSchoonvaere as discussed, we will present the user with a list of species (+ highlights how to recognize these) before they submit an observation. Can you:

- Provide feedback on the list (what should be added/removed/combined + are the Dutch names ok)
- Provide some highlights important for identification (e.g. yellow legs)
- Provide a representative photo for each of the entries (either as an iNaturalist obs we can use or upload in Google Drive)

Related issue: #23

## Individuals

Dutch name | Species | Push to iNat as
--- | --- | ---
Aziatische hoornaar | Vespa velutina | https://www.inaturalist.org/taxa/119019
Europese hoornaar | Vespa crabro | https://www.inaturalist.org/taxa/54327
Wesp (?) | Vespula germanica/vulgaris | https://www.inaturalist.org/taxa/61356
Stadsreus | Volucella zonaria | https://www.inaturalist.org/taxa/343983
Honingbij?? | ... | ...
Insect?? | ... | ...

## Nests

Dutch name | Species | Push to iNat as
--- | --- | ---
Aziatische hoornaar | Vespa velutina | https://www.inaturalist.org/taxa/119019
Europese hoornaar | Vespa crabro | https://www.inaturalist.org/taxa/54327
Wesp (?) | Vespula germanica/vulgaris | https://www.inaturalist.org/taxa/61356
?? | ... | ...

**Comment by Erytran** [comment]
Individuals: take Vv and Vc + those included in https://docs.google.com/document/d/1SKKnvn0di--Uvk05ISSdOoRu4Cw0DexBVV5OXEwBI-o/edit# page 

For species card text you can use the tekst that is below the pictures.

**Comment by Erytran** [comment]
Or is that too much text?

**Comment by timadriaens** [comment]
Dutch name | Species | Push to iNat as
-- | -- | --
Aziatische hoornaar | Vespa velutina | https://www.inaturalist.org/taxa/119019
Europese hoornaar | Vespa crabro | https://www.inaturalist.org/taxa/54327
Duitse/gewone wesp | Vespula germanica/vulgaris | https://www.inaturalist.org/taxa/61356
Stadsreus | Volucella zonaria | https://www.inaturalist.org/taxa/343983
Middelste wesp | Dolichovespula media | https://www.inaturalist.org/taxa/363952
Franse veldwesp | Polistes dominula | https://www.inaturalist.org/taxa/84640
Reuzenhoutwesp | Urocerus gigas | https://www.inaturalist.org/taxa/51560
Blauwzwarte houtbij | Xylocopa violaceae | https://www.inaturalist.org/taxa/124145
Hommels | Bombus | https://www.inaturalist.org/taxa/52775

**Comment by bartaelterman** [comment]
@niconoe Add these species to the migrations so they are created in the database on setup.

**Comment by peterdesmet** [comment]
@KarelSchoonvaere @timadriaens as mentioned via email, please complete the info at https://docs.google.com/spreadsheets/d/1vTFlgHWRFmMyRzIgfkhUdLXdHh0At5f0uMrVUAhrqr4/edit?usp=sharing

**Comment by peterdesmet** [comment]
Species have been added.
