### ISSUE TITLE
Map with autoplay slider

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#145]
Discussed with @timadriaens.

On the homepage we would like to show the invasion of the species on the map. Instead of a slider that can set the start and end date:

- [x] Slider has a **fixed start date** (not shown) and only **one handle** to set the end date, thus showing the cumulative effect of the occurrences. The fact that this doesn't allow to show obs from a specific time period is OK.
- [x] By default the end date **increments automatically**, which:
   - [x] Moves the slider handle to the right
   - [x] Updates the date
   - [x] Updates the map
- [x] The animation pauses, when:
   - [x] The slider reaches the max end date (alternative: keep looping)
   - [x] The user drags the slider
   - [x] The user clicks a play/pause button
- [x] The animation continues (alternative: starts from the beginning), when the user clicks the play/pause button
- [x] The state of the animation (play vs pause) doesn't necessarily need to be shown in the button
- [ ] The map only shows Vespa velutina

@KarelSchoonvaere: what is the official start date for the invasion in Belgium?

**Comment by peterdesmet** [comment]
There will be no related table that needs to be updated with the slider.

**Comment by timadriaens** [comment]
@peterdesmet the first belgian record was 2011

**Comment by Erytran** [comment]
I have a remark. Maybe animated invasion will be a frustration to the people who are actively using the map. Besides, it will become crowded and unclear. In my thinking, map will be used by 3 categories:

1. people actively searching for nests
2. beekeepers who want to know if hornets are signaled in their neighbourhood
3. random people who just want to check the progress/invasion history => need animated map

For the first two categories, the map should only show the seasonal data. I like the idea of the walloon map (http://observatoire.biodiversite.wallonie.be/enquetes/frelon/) where they grey-out the historical reports and colour only the current reports. 

We had 170 reports in 2018, let's take 1000 reports in 2019 and 1000+ in 2020. The animated map will become overcrowded after 2 seasons, rendering it unclear and not usefull anymore. Also, the first record is from 2011, the second is from 2015. This means that there will be a time lapse in the animation where nothing changes. 

Just thinking if it wouldn't be better to go for a static seasonal map like the walloon map (give a different colour to pre-season records).

**Comment by Erytran** [comment]
There is no official start date of the invasion. It can either be the first individual record (2/10/2011) or the first nest record (20-11-2016)

**Comment by timadriaens** [comment]
I though the idea was to have a separate page with more detailed 'statistics': #records per year, #nests per year, #nests destroyed, and to reiterate the map but without the animation, leaving the option to select on year, nest/individual to the user. The animated map can then remain on the homepage as it is imo more engaging for the general public.

**Comment by peterdesmet** [comment]
Let's keep the animated map on the homepage.

@Erytran The user will be able to pause the map and see nest vs individuals. But I agree it would be good to see the data for a certain season. We'll decide later where to do that best.

**Comment by bartaelterman** [comment]
For the first version we'll be focusing on the general public. I think the autoplay that is currently implemented is ok for a first release.
