### ISSUE TITLE
Create thumbnails for observation on creation

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#148]
For the map popup and latest obs, I need a thumbnail at 400x400 pixels (crop longer side). It should be created the moment an obs is created. I could do with just having it for first photo, but having it for all photos of an obs would be nice.

**Comment by niconoe** [comment]
Done! 

Remarks:

- There are new requirements => `pip install -r requirements.txt` to install them
- Example use: https://github.com/inbo/vespa-watch/blob/3937ef18902779ed7335c6f29189edc9f09c6728/vespawatch/templates/vespawatch/individual_detail.html#L53-L58
- You might want to run `python manage.py generateimages` to generate thumbnails for already existing observation pictures.
- Resize with cropping on the long size was surprisingly not available as a preset in django-imagekit. For the moment I choose the "SmartResize" option. I suggest trying this first, we'll implement the "crop long size" manually if the current situation is not good enough.
