### ISSUE TITLE
Latest observations page

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#149]
Create an `obs/` page with an overview of the latest observations (more than 4). Would allow @KarelSchoonvaere to quickly scan incoming information and review on iNat.

**Comment by peterdesmet** [comment]
@niconoe can you start the page and URL, I can then take it from there.

**Comment by niconoe** [comment]
Done: there's a new page, available at `/obs` with some example about how to loop on observations (there are all there, most recent first).

You can generate a link to this page with: `{% url 'latest-observations' %}`.

Good luck!
