### ISSUE TITLE
Synchronize data with iNaturalist

### ISSUE THREAD

**Issue by bartaelterman** [inbo/vespa-watch#15]
See the discussion in [issue 2](https://github.com/inbo/vespa-watch/issues/2).
Then make it happen.

- [x] Create an app account on iNaturalist
- [ ] publish new data on iNaturalist
- [ ] get unknown observations from iNaturalist
- [ ] get updates from known observations from iNaturalist
- [ ] push updates of known observations to iNaturalist

**Comment by bartaelterman** [comment]
@peterdesmet I've send you an email

**Comment by niconoe** [comment]
Closed since it's a duplicate/less precise version of #2.
