### ISSUE TITLE
Add pages for about and identify

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#154]
Two static pages need to be added (already listed in navbar):

- `identification`: https://vespawatch.be/herkenning
- `about`: https://vespawatch.be/vespa-watch

@niconoe how do we want to structure this? Two templates with giant `page_fragments`? That would allow to maintain the content from admin (👍) + provide the text in Dutch and English (👍). I only wonder how _local_ images can be linked from the text.

**Comment by peterdesmet** [comment]
Well, if the images are uploaded to static in the repo, one could link to them.

**Comment by peterdesmet** [comment]
@niconoe can you create the two templates with the correct URL:

url | template
--- | ---
/identification | identification.html
/about | about.html

**Comment by niconoe** [comment]
@peterdesmet : I just added those, with the requested URLs and templates files. I also set two page fragments, it seems to be the right tool for the job! About those page fragments:

- You can actually upload pictures in Page Fragments! In the admin, just drag & drop some images in the field. They'll be uploaded, and a proper URL will be generated in the Markdown code.
- Once you have good initial content for them, we'll probably want to ass the to a migration (see #158)

**Comment by peterdesmet** [comment]
Reopened to test.

**Comment by timadriaens** [comment]
that can certainly be done at a later stage, and we can can discuss this with our walloon colleagues. For now English and Dutch will do fine.

**Comment by niconoe** [comment]
From a technical point of view, I can confirm all the mechanisms are already in place. 

In fact, the texts at the code level are in English, so every Dutch word that you can observe is already technically a translation. Thus, adding French texts at a later stage will be relatively straightforward.

**Comment by peterdesmet** [comment]
About page have been added and are being updated.
