### ISSUE TITLE
Generate pictures in /pictures folder

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#155]
The pictures are currently generated in 3 directories in root:

```
individual_pictures
nest_pictures
taxon_identification_pictures
```

I think it would be nicer if we could group this to:

```yml
pictures/ # Or images, photos, ...
- nests/ # Or nest
- individuals/ # Or individual
- identification_cards/ # Or identificationcard
```

**Comment by niconoe** [comment]
Fixed, you'll need to reupload pictures on your development machines (the path are stored in the database).
