### ISSUE TITLE
Add footer

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#156]
Add a footer to base.html, so it is displayed **on every page**. Should include some links:

- TOS
- Partner links/logos
- Developed by LifeWatch INBO
- @KarelSchoonvaere anything else?

**Comment by timadriaens** [comment]
the following partners/text should be mentioned in the footer:

INBO
Honeybee Valley (https://www.honeybeevalley.eu/)
"met financiële steun van het Departement Economie, Wetenschap en Innovatie" (or their logo + link underneath)

**Comment by peterdesmet** [comment]
Footer added in https://github.com/inbo/vespa-watch/commit/1c212cd77dae4246c5b1088800105317d21d5bf2
