### ISSUE TITLE
Export data

### ISSUE THREAD

**Issue by bartaelterman** [inbo/vespa-watch#16]
Updated by @peterdesmet:

Allow logged in admins to download relevant data via a button in the admin interface. Requirements:

## General

- Data as csv
- No filtering
- Include all fields (for now)
- Sort by id

## Individuals

- Add button to nests individuals page

## Nests

- Include columns from management data (one-to-one, so same number of records)
- Add button to nests admin page

**Comment by niconoe** [comment]
Indeed! @peterdesmet , @timadriaens , @stijnvanhoey : don't hesitate to already start think about the exports: 

- Who are they for? one or several group of people?
- For which usage?
- Is CSV format okay at first, or do you need fancier things?
- Main fields to include in CSV? Should this be (per export) configurable?
- ...

**Comment by peterdesmet** [comment]
Observations can already be [exported from iNaturalist](https://www.inaturalist.org/observations/export?projects=vespa-watch). I know you need to be logged in for that, @niconoe can you test if that link is available for a non-project owner?

Still, Vespa-watch contains more information than what is pushed to iNaturalist, including user data (who did what) and management actions: that information should be only be available to the project owners (i.e. super user) ideally as csv: can that be retrieved from the backend.

As a second step, offering a csv file with the observations from the vespa-watch website without requiring a login would be nice.

**Comment by timadriaens** [comment]
upon providing feedback on the survey, it is impossible to export non-Vespa velutina data from iNaturalist (see eg the donwload [link](https://www.inaturalist.org/observations/export?projects=vespa-watch)). This should be possible from the Vespawatch admin site.

Question: what if the species reported does not appear on this list (e.g. Cimbex, Tipula etc.) : I take it this is still added in Vespawatch?

FILTER
By taxon
All
Vespa velutina
Urocerus gigas
Bombus
Xylocopa violacea
Volucella zonaria
Dolichovespula media
Polistes dominula
Vespula vulgaris
Insecta
Vespula germanica
Vespula vulgaris/germanica
Vespa crabro
-

**Comment by peterdesmet** [comment]
@timadriaens yes, unknown species are still added to VespaWatch, with their iNat scientific name.

**Comment by peterdesmet** [comment]
@KarelSchoonvaere @timadriaens would it be ok to download nests and individuals separately, or do you want it combined?

**Comment by KarelSchoonvaere** [comment]
This is question for Tim. 
From my experience, it is handy to have both nests and individuals in the same file + possibility to filter by column that holds either nest/individual.

**Comment by niconoe** [comment]
There's now a basic export feature (in `csv_export` branch, see pull request):

![image](https://user-images.githubusercontent.com/386387/60005521-fa372e00-966e-11e9-8557-65ec092a1c98.png)

It appears as an "export" button in the Admin, when looking at the list of Nests and Individuals. You can filter by a specific taxon (right column) before pushing the export button. Several formats are available.

@timadriaens / @KarelSchoonvaere : just tell me if you need more! Small changes (add/remove fields, ordering, column names, ...) are very easy to implement, merging nests and individuals in a single file will require extra work, but is of course perfectly doable if needed!

**Comment by peterdesmet** [comment]
I'm trying to push this to uat, so it can be tested.

**Comment by peterdesmet** [comment]
@KarelSchoonvaere @timadriaens can you test this functionality at https://uat.vespawatch.be/admin/vespawatch/individual/ ?

**Comment by timadriaens** [comment]
what is the login/pwd for that uat? I cannot login with timadriaens - 19TimA!b

**Comment by timadriaens** [comment]
Looking ok. A few remarks:

- the field taxon is perhaps redundant with taxon_name
- what does 'inat_vv_confirmed' mean?
- observer name, email and phone are always empty?
- values for behaviour (OT, HU...) but mostly empty like individual_count?
- only 141 records of Vespa velutina & Vespa crabro for 2019, why are the other species not fed back into vespawatch? It would be nice to have stats for other species reported through the website.
- validation stats: possibility to include this or does it have to come from iNaturalist?

**Comment by peterdesmet** [comment]
@timadriaens @KarelSchoonvaere the export button is now deployed on [production](https://vespawatch.be/admin/vespawatch/), meaning you can download live data. Note that the sync with iNaturalist is currently blocked due to account suspension.

@timadriaens most of the remarks you report are because you were testing this on non-production data. For production:

- `taxon` is the id, `taxon_name` the name (if known by VespaWatch). It doesn't hurt to have both.
- `inat_vv_confirmed`: a confirmed Vespa velutina by iNaturalist community (1: true)
- observer name, email and phone or not empty , but missing for a period of time when these fields were not mandatory
- behaviour and individual count are not empty
- Other species ARE fed into vespawatch, their taxon/taxon_id will be empty if not recognized by Vespawatch, but they will have an `inaturalist_species`
- Validation stats are limited to `inat_vv_confirmed`
