### ISSUE TITLE
homepage footer information

### ISSUE THREAD

**Issue by timadriaens** [inbo/vespa-watch#161]
the following partners/text should be mentioned in the footer:

INBO
Honeybee Valley (https://www.honeybeevalley.eu/)
"met financiële steun van het Departement Economie, Wetenschap en Innovatie" (or their logo + link underneath)

**Comment by stijnvanhoey** [comment]
(only close when work is done ;-)

**Comment by peterdesmet** [comment]
@stijnvanhoey was added as a comment to other issue: https://github.com/inbo/vespa-watch/issues/156#issuecomment-457590521
