### ISSUE TITLE
Add form_url to identification card + link on picture

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#168]
In `obs_create.html` I'm creating the form url as:

https://github.com/inbo/vespa-watch/blob/36b3390dbf7b63c90ca0fd7ecb82efe5125ee05d/vespawatch/templates/vespawatch/obs_create.html#L35-L39

I need to do this for the image too and thought all this might be better set in the `identification_cards` view instead. 😁 

@niconoe, can you return `form_url` for `identification_card`? You can leave the `&redirect_to=index` out, as this is really a template property.

**Comment by niconoe** [comment]
Hmmm, `identification_card` is an instance of the `IdentificationCard` model, not a view...

So yes, I can easily return the `form_url` (which is actually a view URL) as a property of it, but I think its actually a bit worse than the current situation, architecturally speaking :) (more model/view coupling) That being said, it will probably not break anything so I'll definitely do it if you insist!

(in general, the code is full of "`if nest do_something else do_almost_the_same`", but that is an unavoidable consequence of the individual/nest split at the model level -  I sometimes still have doubts about this, months later).

Just tell me what you prefer and I'll fix it ASAP!

**Comment by peterdesmet** [comment]
It's fine. I have used `if` in the `identification_card` template:

https://github.com/inbo/vespa-watch/blob/66c3ff8f0fdd78748e5cc4a819e0d2da6b50f65a/vespawatch/templates/vespawatch/includes/identification_card.html#L6-L10
