### ISSUE TITLE
Infrastructure

### ISSUE THREAD

**Issue by bartaelterman** [inbo/vespa-watch#17]
- [ ] CI/CD (Check with @stijnvanhoey )
- [ ] test server / production server
- [x] automated backups
- [x] use an s3 bucket as static server. At least for images, but it might make more sense to also put other static stuff in the same bucket.

**Comment by niconoe** [comment]
We'll probably need to make use of [django-storages](https://django-storages.readthedocs.io/en/latest/index.html) to use S3 for static/media files. (I'll have a quick look for alternatives, but I think it's the standard/well supported solution).

**Comment by bartaelterman** [comment]
To be discussed I would say. If we go for an RDS, you can just enable backups. If we go for a database on the VM, we need a bucket to dump the backups.

**Comment by stijnvanhoey** [comment]
Development is running as elastic beanstalk environment, http://vespawatch-dev.eu-west-1.elasticbeanstalk.com/.

**Comment by stijnvanhoey** [comment]
media files are pushed to inaturalist, so this is an additional backup of the images

**Comment by stijnvanhoey** [comment]
I'd like to close this issue and moving specific elements to individual issues. One item to discuss first is CI/CD. 
- @bartaelterman do you have anything to 'test' apart from deploying and checking the result? Would it make sense to setup any CI tool for testing elements?
- With respect to future deployment process. We keep deployment to prd *manual* and have a hook to continuously deploy master-branch to development? Or do we have better options considering the specifics of this project?

**Comment by bartaelterman** [comment]
- so far we have no tests, but I do would like to add those. However, let's adapt the CI/CD when needed and close this issue for now.
- deployment to production should indeed not be fully automated. Preferably it's a single command to execute or one button to click on.

**Comment by stijnvanhoey** [comment]
The single button/command for deployment is `eb deploy`, so that's fine. As we have no tests, closing for now.
