### ISSUE TITLE
Split about page in sub pages

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#174]
There is quite a lot of text for the about page, that is best split over multiple pages. What we need is:

url | todo | how to get URL
--- | --- | ---
about/ | @peterdesmet update template to tiles with subpages | `{% url 'about' %}`
about/project/ | @niconoe create template and page_fragment | `{% url 'about_project' %}`
about/activities/ | @niconoe create template and page_fragment | `{% url 'about_activities' %}`
about/vespa-velutina/ | @niconoe create template and page_fragment  | `{% url 'about_vespavelutina' %}`
about/management/ | @niconoe create template and page_fragment |  `{% url 'about_management' %}`
about/privacy-policy/ | @niconoe create template and page_fragment (replaced terms_of_service!) |  `{% url 'about_privacypolicy' %}`
about/links/ | @niconoe create template and page_fragment |  `{% url 'about_links' %}`

**Comment by niconoe** [comment]
I just added a column telling how to generate links to those page in templates.

**Comment by niconoe** [comment]
@peterdesmet : should we remove the "terms_of_service_modal.html" template and all related code?

**Comment by niconoe** [comment]
New pages created as requested:

- You'll need to run `python manage.py migrate`
- To keep things in order, I consider the removal of `terms_of_service` page fragment and related code (views, template, link to modal, ...) a second task. I'll perform this once I have confirmation all that should disappear.

**Comment by peterdesmet** [comment]
Yes, the intention is to remove all terms_of_service_modal code, but I’d like to test the rest first.

**Comment by bartaelterman** [comment]
I've changed the navigation element for the about pages. They now point to the different about pages and the main about page is removed. They all use the `simple_page_fragment.html` template, with a different page fragment id. See d7b041eb5a51ff7c9950727837ac1c2978a3c097

**Comment by peterdesmet** [comment]
Done.
