### ISSUE TITLE
Deploy with SSL/HTTPS

### ISSUE THREAD

**Issue by niconoe** [inbo/vespa-watch#182]
We should decide if we want to deploy over HTTPS:

Pros
- Is getting more and more standard, browsers now show "this website is not secure" over HTTP and visitors expect it from a "serious website"
- Geolocation (needed for the report form) will not work (at least reliably/consistently/everywhere/in the long term)

Cons
- May be more complex to deploy
- We need to test it soon (risk of things breaking here and there)

I've had some good/easy experiences with Let's encrypt! certificates, but that was on a standard server, not AWS.

@stijnvanhoey and @peterdesmet, what do you think?

**Comment by peterdesmet** [comment]
I would say `https`, especially since there is a login part too. Don't know what that entails for deployment though.

**Comment by niconoe** [comment]
@bartaelterman just told me the exact same thing, I was coming there to log it (and I also agree we should try it).

**Comment by stijnvanhoey** [comment]
We certainly will deploy using `https`, something @berthuygens will take into account on the UAT/PRD level

**Comment by bartaelterman** [comment]
@stijnvanhoey Is there something we need to do on our side?

**Comment by niconoe** [comment]
Thanks, it would be great to have it in some pre-prod environment (dev? uat?) so we can check:

- That #169 works fine once we are in a secure environment
- Generally speaking, that nothing else gets broken (thinking of stuff like AJAX request, CORS, ...)

**Comment by stijnvanhoey** [comment]
The UAT is live: https://uat.vespawatch.be/

**Comment by peterdesmet** [comment]
Is done.
