### ISSUE TITLE
Check management page map after refactor for #157

### ISSUE THREAD

**Issue by bartaelterman** [inbo/vespa-watch#186]
After refactoring to improve performance (see #157 ), I have not tested the impact on the management page. We should check:
- the map still loads as expected
- the API is not called too much (I checked, it does...)
- all information for the table is gathered from somewhere

**Comment by niconoe** [comment]
When doing so, could you also check the management action modal (to add/edit/delete a management action per nest) still works as expected?

**Comment by peterdesmet** [comment]
Management page will be different (is currently broken too), will be tackled in separate issues.
