### ISSUE TITLE
page fragments initial setup

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/vespa-watch#187]
To provide the site content (about pages,...) with the page fragments, we could do this as part of the initial setup, cfr. #158. However, some elements to consider:
- when images are required, these should be moved to S3 (subfolder `markdownx`) to include these. technically not an issue, but additional config during setup.
- having some prefilled information on DEV level is convenient (so, develop environments don't have to provide page fragments to get started or see something)
- having a lot of content pre-filled during setup could provide issues, as the content would be stored in 2 locations (dbase + static/py files for setup), leading to issues when updating (adapt in dbase without taking into account static content?!?).

So, we target to have:
- content for the website is managed on dbase level only (after setup in PRD just fill in everything)
- the initial setup contains placeholders for the different content sections, so it is clear after initial setup and on dev-level where page fragments are, cfr. https://github.com/inbo/vespa-watch/blob/1d3b5a5adfb787e170afb55b491b8f0309f02516/vespawatch/migrations/0002_initial_data.py#L8-L18

**Comment by stijnvanhoey** [comment]
Todo: make sure placeholders are available for each of the required page fragments

**Comment by peterdesmet** [comment]
Page fragments are being used.
