### ISSUE TITLE
Filter on identification_card nest/obs

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#190]
@niconoe is there a way to filter on nest vs obs in:

https://github.com/inbo/vespa-watch/blob/d18edf571751a735fdc7957785d9fc25f54ffdf2/vespawatch/templates/vespawatch/obs_create.html#L17

**Comment by niconoe** [comment]
Yup!

`{% if card.represents_nest %}...{% else %}...{% endif %}`
