### ISSUE TITLE
Email of username for login?

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/vespa-watch#193]
Currently, the login provides field for email address and password:
![image](https://user-images.githubusercontent.com/754862/53976142-ba235e00-4106-11e9-8188-aaf441343c39.png)

whereas we use login names for the firefighters accounts only. Should we adapt the setup of accounts or use `user name` instead of `email`?

**Comment by KarelSchoonvaere** [comment]
Personally I prefer to use both. Can the field be made redundant?

**Comment by peterdesmet** [comment]
The moment a firefighter account is used, we will add an email, so they can login with email.

**Comment by niconoe** [comment]
The system allows of course to configure an e-mail address for each user account, by default Django uses the username/password combination to log users in, and the mail field is just optional information.

Given that and the "email as login" requests, I think what we need to do is:

- [ ] Customize the authentication mechanism so it works with mail/password pairs (in addiiton or in place of the username/password pairs)
- [ ] Get from the firefighters an email address for each zone?
- [ ] Update the zone creation script so it sets those email addresses for each created account

Does that sounds correct?

**Comment by peterdesmet** [comment]
Login via email would probably easier if we have registered "control operators"

**Comment by peterdesmet** [comment]
Login via email would still be good. Moving this to proper milestone.

**Comment by bartaelterman** [comment]
Does this mean we also have to confirm that the email is a valid email address?
Do we have to validate this email address in any way?

**Comment by peterdesmet** [comment]
If we validate email addresses, this should be done on registration (#322). Is there a Django plugin for this?
