### ISSUE TITLE
Models/business logic: "sync-related" things to check

### ISSUE THREAD

**Issue by niconoe** [inbo/vespa-watch#197]
- [x] That observations created in the app form have the `originates_in_vespawatch` flag set (and if created in the admin, it is also forced to true)
- [ ] check `can_be_edited_or_deleted` and `taxon_can_be_locally_changed`: are they still in use or useful? If not, delete.
- [x] set and push vespawatch_behaviour on 1srt push of our observations (skipped for now, see #98)
- [ ] InatObsToDelete: make sure it's populated correctly (when we delete of our VW-originating obs, not when locally deleting an obs from iNaturalist)
- [ ] Various TODOs in `inat_sync.py`

**Comment by bartaelterman** [comment]
Closing this one. Most of it is covered in #2
