### ISSUE TITLE
Figure out the synchronization with iNaturalist

### ISSUE THREAD

**Issue by bartaelterman** [inbo/vespa-watch#2]
We'll push our observations to iNaturalist to make our data accessible. And we want use the iNaturalist community to be aware of new observations or improved identifications.

> The basic idea: through vespawatch observations are only created or deleted, any management of observations is done by the iNat community (including the `vespawatch` iNat user). The other main purpose of the vespawatch is to log management actions (which is why observations are never automatically deleted on pull).

## Obs created in vespawatch: nest or individual

- [x] Preliminary task: delete at iNat if recently deleted in our DB
- [x] Detected by: filter our local database on`originates_in_vespawatch=TRUE`
- [x] Editable in admin: yes, until 1st push (until has `inat_id`). Deletion is always possible.
- [x] 1st push (has no `inat_id` yet): create obs under user `vespawatch` with `inat_taxon`, `date`, `location`, `description`, `photos`, `vespawatch_behaviour` (and assign `inat_id` in our DB).  We also set `vespawatch_id` (useful for traceability) and `vespawatch_evidence` (for consistency with pull operations of inaturalist records).
- nth push (has `inat_id`):
    - [x] obs found: do nothing
    - [x] obs not found: do nothing (warning is handled via pull)
- Pull
    - [x] query iNaturalist  on: `inat_id`
    - obs found: update all information again and set `inat_vv_confirmed` (note: this might change the location of a nest, remove the `vespawatch_behaviour` or hide the obs from firefighters) 
    - [x] obs not found (deleted by Vespawatch iNat user): leave in DB, flag with warning.

## Obs created through iNaturalist to be harvested: individuals & nests

- [x] Detected by: not in DB
- [x] Push: there is no push
- [x] Pull:
    - [x] select on: in Vespa-watch project and _Vespa velutina_ (`project_id=22865&taxon_id=119019`) and `inat_id` is not yet in our DB (in both tables)
    - [x] if `vespawatch_evidence=nest`: create obs in our DB as nest with `inat_taxon`, `date`, `location`, `description`, `photos`,  `inat_id` and `inat_vv_confirmed`
    - [x] else: create obs in our DB as individual with `inat_taxon`, `date`, `location`, `description`, `photos`,  `inat_id` and `inat_vv_confirmed`

## Obs created through iNaturalist and harvested before: individuals & nests

- Detected by: `originates_in_vespawatch=FALSE` and has `inat_id`
- Editable in DB: never. Deletion is always possible.
- Push: there is no push
- Pull:
    - select on: `inat_id`
    - obs found: update all information again and set `inat_vv_confirmed`
    - obs not found (deleted by iNat user): leave in DB, flag with warning
    - Note: if the `vespawatch_evidence` info is updated at iNat _after_ a pull, it will remain (incorrectly) as nest or individual in our database. If we notice this, we can always remove it from VespaWatch and the next pull will create it as the correct nest or indiv.

## ~~Update a iNat obs to a nest~~

- ~~This is not a sync action, but an action in which an individual is changed to a nest (never in the other direction): new nest is created, all information is copied, individual is deleted.~~
- ~~Only possible for super users through vespawatch app (frontend)~~

See https://github.com/inbo/vespa-watch/issues/2#issuecomment-455156639

**Comment by niconoe** [comment]
Good points. A few additional ones:

- Does iNaturalist have a sandbox environment where we can play without messing with real data?
- We can use [tags/annotations/projects/...](https://www.inaturalist.org/pages/annotations) (or a combination of all those) to push our data to iNaturalist. Attaching our own ID to a given observation may be useful for example.
- Since we need 2-ways sync, in some cases things can become difficult. I think it's wise to NOT try to solve every single edge case and focus on a robust mechanism for 95%+ of cases + a good "manual fix when needed" approach.
- It's important to have excellent logging capabilities for those features so we can analyze/fix things post-mortem, if needed.
- I'd probably implement the sync as a (or a pair of) custom Django management commands, to be executed frequently and run in a task queue.

**Comment by niconoe** [comment]
I'll try to write a very basic sync command soon, to already retrieve data from iNat (filter based on the project, probably).

**Comment by bartaelterman** [comment]
I wonder whether it would make sense to keep iNaturalist fields separate from our own fields. That way, syncing becomes easy: you only overwrite those fields. When displaying data (for instance on the map) you check whether you have a species name from iNaturalist and if not, the app uses the internal field.
For internal updates, we can keep a field "updated-since-last-sync" and only push observations that have been changed.
That way, I think we can avoid the conflict issue we discussed.

**Comment by niconoe** [comment]
That's an interesting approach, I'll keep it in mind while concretely exploring all this!

**Comment by niconoe** [comment]
FYI: Just made a (very naive/incomplete) first iteration of a Django command that retrieves observations from the iNaturalist project and store them in the Django database. Learned a lot of things and took some notes about the API, already.

**Comment by bartaelterman** [comment]
@niconoe closing this issue. Most of the remaining stuff is covered in other issues.

**Comment by bartaelterman** [comment]
@peterdesmet @stijnvanhoey could you reconfirm what we would do when we pull taxon information from iNaturalist:
- overwrite our own taxon information
- keep a separate inaturalist_taxon field and only update that. This keeps our own taxon in place.

I thought we agreed on option 2 but I can't recall what the added value is of keeping the original taxon.

**Comment by peterdesmet** [comment]
Decided with @KarelSchoonvaere that any incoming observation from iNat that is actually a nest, will be created/duplicated **manually** in Vespawatch by coordinator (copying information into obs submission form). Only we notice that the number of nests recorded via iNaturalist is too much, we will consider creating a more streamlined approach.

**Comment by niconoe** [comment]
Before we can release, we'll need to:

- Carefully checks everything here (first comment) is still true and consistent (after the discussions with the firefighters and other evolutions)
- Implement it (currently: very old code, doesnt't do we want anymore)
- Make basic tests

**Comment by niconoe** [comment]
@peterdesmet : can you help me reviewing the detailed sync description in the first comment point by point, to make sure it still fits the latest changes and discussions? The current sync code is REALLY old and I think  we need something decent before release, so I'm considering ditching the whole stuff and reimplementing from scratch according to this description.

But it's a large task, hings have already changed a lot and that the devil's in the details (especially for code like that), I'd like to have some reassurance I'm implementing the right stuff first! thx!

**Comment by peterdesmet** [comment]
@niconoe just checked it again and seems all good to me.
