### ISSUE TITLE
show pictures of latest observations

### ISSUE THREAD

**Issue by bartaelterman** [inbo/vespa-watch#20]

**Comment by peterdesmet** [comment]
@niconoe I’ll also need per obs:

- detail page url
- inat url (see #147)
- type (nest/individual)
- inat_vv_confirmed

**Comment by peterdesmet** [comment]
Looks done on homepage, but still need the elements described above.

**Comment by niconoe** [comment]
... and the subject: 

`{{ my_observation.subject }}`

**Comment by peterdesmet** [comment]
Great, although `detail_page_url` is more consistent (without `get_`). Remaining task for this issue to be closed: `inat_vv_confirmed` flag (#139)

**Comment by peterdesmet** [comment]
Flag `Confirmed` is now added.
