### ISSUE TITLE
Translate form labels

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#200]
Test if field names are added to `.po.`  files for:

- `models.py`: `verbose_name=_("My text")`
- `models.py`: fields without a verbose name

**Comment by niconoe** [comment]
...And also test if Crispy forms display the translated strings :)

**Comment by peterdesmet** [comment]
Should be done in https://github.com/inbo/vespa-watch/commit/ad6867cdec901d8073fa241d0f9e8ab2df745d43

**Comment by peterdesmet** [comment]
Is done.
