### ISSUE TITLE
Creates an iNaturalist client Python package?

### ISSUE THREAD

**Issue by niconoe** [inbo/vespa-watch#21]
As I started to work with the iNaturalist API for our application, I noticed:

- I couldn't find an existing Python package to access the iNaturalist API (so we have to "manually" access the API with HTTP requests)
- The code we'll implement (example: a `get_all_occurrences()` function that allows doing `get_all_occurrences(project_id=2268, species="Vespa Velutina")`) for this is not project-specific and probably useful for others.

I was therefore wondering if it wouldn't be a good idea to already give it its own life: own repository (ideally with basic docs and tests), Python package available on PyPI, ... Of course we would only implement for the moment the parts we need for Vespa-Watch to keep the workload low, but at least we'd already have an interesting derived product that maybe others can use and improve.

Any opinions on that?

**Comment by stijnvanhoey** [comment]
I do like the idea. If we consider it for the moment as a very minimalistic package (considering the timing we're working with, this probably should not be too much overhead.

**Comment by peterdesmet** [comment]
I do like that idea too. Should start as a repo under the INBO org. Suggestions for the name?

**Comment by niconoe** [comment]
Cool! 

About the names, I just read [this guide](https://legacy.python.org/dev/peps/pep-0423/). In particular I'd like to have a single name that works for python package, PyPI entry, repository, ... so things are clear. I also would like the name to be immediately clear to both the iNaturalist and Python community. 

So I was thinking of `pyinaturalist` (or `pyinat` maybe), following the `pygbif` model. But you may have better ideas!

**Comment by peterdesmet** [comment]
The R package is called [`rinat`](https://github.com/ropensci/rinat), but I don't see `inat` being used a lot as an abbreviation. iNaturalist uses the full name in almost all [their repositories](https://github.com/inaturalist), so I'm inclined to say `pyinaturalist` (`pynaturalist` sound easier, but is harder to search 😄)

**Comment by niconoe** [comment]
everybody agrees wirh `pyinaturalist`? Should we create the repo? I'll be ready soon to push a VERY incomplete first alpha version.

**Comment by peterdesmet** [comment]
Created and granted access at https://github.com/inbo/pyinaturalist
