### ISSUE TITLE
observations overview during inaturalist sync

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/vespa-watch#212]
The current sync with inaturalist takes a couple of minutes and these observations are not visible on the website during the synchronization. This confuses the user... Should be taken into account for the new sync operation (make sure the replacement itself of the observations is fast, only overwrite when necessary,...).

**Comment by stijnvanhoey** [comment]
Notice also the amount of traffic the update of observations currently takes:

![image](https://user-images.githubusercontent.com/754862/54901558-1d6b0980-4ed7-11e9-96e7-9b9bb63c910e.png)

**Comment by bartaelterman** [comment]
We're downloading the images, so I think it's ok to see this amount of traffic the first time. However, after that I would expect it to decrease drastically. We'll look into it when resolving #2

**Comment by bartaelterman** [comment]
Also, @stijnvanhoey I'm not sure what you mean with `this confuses the user`. I mean, I understand your sentence, but what exactly is confusing? Maybe we should pick this up on a next meeting.

**Comment by stijnvanhoey** [comment]
Well, with _confuses_ I mainly think that it is strange for a user that in those 15 minutes the `latest` observations are continuously changing on page refresh or changing pages. 

With respect to the download, I do think this should be taken into account while tackling #2 as currently there is no decrease in download in between sync.

**Comment by peterdesmet** [comment]
New sync doesn't affect website.
