### ISSUE TITLE
JS error: translated api call?

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#213]
On the Dutch version of my local vespawatch I get the JS error:

```
jquery.min.js:2 GET http://localhost:8000/api/individus/753 404 (Not Found)
```

The `url` seems translated (`individus`) where it should be. Will have to see if this occurs on production.

**Comment by peterdesmet** [comment]
Tackled, should be tested in production.

**Comment by stijnvanhoey** [comment]
updating...

**Comment by peterdesmet** [comment]
Fixed.
