### ISSUE TITLE
Narrow scope of observations in map to vespa velutina

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/vespa-watch#214]
Currently, the map also show the European hornet. As noticed by @KarelSchoonvaere, we agreed to have only the vespa velutina as observations in the map.

(For the latest observations, we still show all observations so freshly added are directly shown on the website).

**Comment by peterdesmet** [comment]
I think is now fixed, because the scope of the inat project is now Vespa velutina in Belgium only.
