### ISSUE TITLE
Add compilemessages command to deployment

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/vespa-watch#215]
In order to make sure the language translations are properly created, we need an additional command during AWS deployment:

```
python manage.py compilemessages
```

To make this work, we have an additional dependency:

```
yum -y install gettext
```

This boils down to adding the command in [config](https://github.com/inbo/vespa-watch/blob/master/.ebextensions/01_python.config#L50) and `gettext`
 as dependency in [package config](https://github.com/inbo/vespa-watch/blob/master/.ebextensions/02_packages.config). 

@berthuygens I'll do the adaptations and ping you to redeploy on prd when ready.

**Comment by stijnvanhoey** [comment]
@berthuygens I fixed the language issue and tested succesfull on uat. Can you redeploy (`eb deploy`) to production? Thanks!

**Comment by peterdesmet** [comment]
Is fixed in production.
