### ISSUE TITLE
Latest observations on bottom of page are older than the observations on overview page

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/vespa-watch#218]
When looking at the current homepage:

![image](https://user-images.githubusercontent.com/754862/54991592-8f1d8300-4fbd-11e9-9196-248026ddc30c.png)
latest observation shown is 2018-10-12, whereas the real latest observation is 2019-03-19. It seems the latest observation is even older than the observations in https://vespawatch.be/obs/

**Comment by bartaelterman** [comment]
bug found. That solves it locally. Hopefully also resolved on other environments @stijnvanhoey ?

**Comment by peterdesmet** [comment]
Rather than closing, it's better to add label `to test` to verify it is solved in production.

**Comment by peterdesmet** [comment]
Seems solved.
