### ISSUE TITLE
Cannot add push/pull ids for taxa

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#223]
It should be possible to edit `Inaturalist pull taxon ids` and `Inaturalist push taxon id` in the admin interface. That is currently not possible:

<img width="592" alt="Screenshot 2019-03-26 at 12 04 46" src="https://user-images.githubusercontent.com/600993/54992400-7c0bb280-4fbf-11e9-89b4-41de832f6f75.png">

As a result, many observation cannot be pushed to iNat.

**Comment by bartaelterman** [comment]
They are explicitly set to `readonly` in [the admin file](https://github.com/inbo/vespa-watch/blob/master/vespawatch/admin.py#L16). Any idea why? It's quickly removed but might be good to think twice.

**Comment by peterdesmet** [comment]
I do not know why, but if they are changed the worst that would happen is:

- Pushed to iNaturalist with new species => new (wrong) identification added. Can be reverted.
- Pulled from iNaturalist as a species that is not recognized => New sync will flag them as `taxon not in list`

So I don't see much harm.

**Comment by bartaelterman** [comment]
Done. Beware that pull taxon ids is a comma separated list

**Comment by peterdesmet** [comment]
Ok, missing ids are now added in production.
