### ISSUE TITLE
Images in page_fragments are automatically resized

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#229]
Images that are drag/dropped into page_fragments get automatically resized to 72dpi (good) and resized to max 500px (not good: would prefer a bit wider). @niconoe where is this setting defined?

**Comment by bartaelterman** [comment]
@peterdesmet can you try adding the [MARKDOWNX_IMAGE_MAX_SIZE](https://neutronx.github.io/django-markdownx/customization/#markdownx_image_max_size) to the [base settings file](https://github.com/inbo/vespa-watch/blob/master/djangoproject/settings/base.py)? I haven't tested it myself. Hope this helps

**Comment by peterdesmet** [comment]
Done in https://github.com/inbo/vespa-watch/commit/a89bc6da6924b5dc50f77bee3ec7ab1ee60c37cf
