### ISSUE TITLE
Controlled vocab for species

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#23]
Taxa that can be added via website:

scientific name | vernacular name | `inaturalist_push_taxon_id` | `inaturalist_pull_taxon_ids` | translation
--- | --- | --- | --- | ---
Vespa velutina | Asian hornet | https://www.inaturalist.org/taxa/119019 | | Aziatische hoornaar
Vespa crabro | European Hornet | https://www.inaturalist.org/taxa/54327 | | Europese hoornaar
Vespula germanica |  German Yellowjacket | https://www.inaturalist.org/taxa/126155 | | Duitse wesp
Apis mellifera | Honey Bee | https://www.inaturalist.org/taxa/47219 | | Honingbij
Insecta | Insect | https://www.inaturalist.org/taxa/47158 | | Insect

@timadriaens @KarelSchoonvaere please add more if needed

**Comment by niconoe** [comment]
Currently implementing this in the Django Species model. We'll have a `inaturalist_push_taxon_id` field used when pushing our own observations to iNaturalist, and `inaturalist_pull_taxon_ids` (an array) so we can reconcile several taxons from iNaturalist (for example a subspecies of Vespa Velutina) to a single species on our side.

Also:
- We use django-modeltranslation to have vernacular names in English and Dutch
- We'll populate this initial data with a migration/fixture so everyone has the same.

**Comment by peterdesmet** [comment]
Update table to reflect choices.

**Comment by timadriaens** [comment]
please use 'Asian hornet' for Vespa velutina instead of 'Asian Predatory Wasp' it is more commonly used

**Comment by peterdesmet** [comment]
Updated in issue body and homepage 999c550

**Comment by bartaelterman** [comment]
@niconoe Looks like there is a migration file for this so I think most of it is done. Could you just replace "Asian Predatory Wasp" by "Asian hornet" as requested by Tim?
