### ISSUE TITLE
What is js_config_object

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#232]
@niconoe what is this:

https://github.com/inbo/vespa-watch/blob/0e1a68cd202964a4bcf2b10cc5beac3db433d3a5/vespawatch/templates/vespawatch/base.html#L14-L16

If required, can that JS code be moved to the bottom of the template, like all JS scripts?

**Comment by bartaelterman** [comment]
It's a custom template tag, used to read some values from the settings and make them available to the JS: https://github.com/inbo/vespa-watch/blob/master/vespawatch/templatetags/custom_tags.py

**Comment by niconoe** [comment]
As @bartaelterman sayed! It sets configuration used by... many different pieces of the puzzle. So:

- You can try moving it to the bottom of the template if you prefer
- But make sure it appears before any other piece of JS code
- And test extensively that nothing is broken on the frontend side afterwards (Vue components for example)

**Comment by niconoe** [comment]
As far as I understand this is doing the job and will not change for the foreseeable future, so closing for now.
