### ISSUE TITLE
Obs of 19 March not pulled with photo

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#234]
The latest observation of 19 March 2019 has a photo on iNaturalist (https://www.inaturalist.org/observations/21414496) but not on the website (https://vespawatch.be/obs/). Any idea what caused this (file permissions, etc.)?

**Comment by stijnvanhoey** [comment]
The strange thing is that this is different for the english versus the dutch translation? Can you verify that on the english version the photo actually is shown?

**Comment by peterdesmet** [comment]
Indeed, correct. 🤔

**Comment by peterdesmet** [comment]
Pretty sure it is related to https://github.com/inbo/vespa-watch/issues/213

**Comment by peterdesmet** [comment]
Only occurs for individuals, not nests

**Comment by peterdesmet** [comment]
Tackled, will be tested in production for #213.
