### ISSUE TITLE
Detect current position

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#236]
@KarelSchoonvaere notified me that "detect current position" does not show the correct place. For me (@peterdesmet) it doesn't work at all.

**Comment by timadriaens** [comment]
It does work on my laptop both for nests and individuals, but indeed does not work on my samsung galaxy.

**Comment by bartaelterman** [comment]
Can we mark this as a duplicate of #169 ?

Also, this is a functionality where we have very limited control. We merely rely on the browsers implementation of the geolocation API. I don't think we'll be able to fix this for all browsers / all devices.

**Comment by peterdesmet** [comment]
Yes, this is a duplicate. Closing
