### ISSUE TITLE
Link from latest observation to iNaturalist not working

### ISSUE THREAD

**Issue by KarelSchoonvaere** [inbo/vespa-watch#238]
The latest observation of a wasp is presented on the homepage but remains with status "not yet synchronized" instead of having the link to iNaturalist. On iNaturalist I can't find the observation.

**Comment by peterdesmet** [comment]
That is because observations are not yet pushed to iNaturalist (only pulled). They will once that is implemented. @bartaelterman, any idea when you’ll be able to pick this up?

**Comment by bartaelterman** [comment]
I'll work on this issue next Thursday.
