### ISSUE TITLE
Report link at about/vespa-velutina does not work

### ISSUE THREAD

**Issue by bartaelterman** [inbo/vespa-watch#239]
- go to [https://vespawatch.be/about/vespa-velutina/](https://vespawatch.be/about/vespa-velutina/)
- scroll all the way down
- click the link `Report` in the last paragraph.
- the link points to `about/obs/add/` but the `about` should be removed from that link.

I also noticed we have a trailing slash issue here. It's a best practice to define all urls with trailing slash in the `urls.py` files. If you browse to a url without the trailing slash, it is redirected to the one with the trailing slash. The opposite does not work as demonstrated by the example above. I'll pick up the trailing slashes later.

**Comment by peterdesmet** [comment]
Corrected in text. Leaving open for you to fix trailing slashes.
