### ISSUE TITLE
Error on terms of service

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#243]
Reported and confirmed. When submitting an observation as a non-logged-in user, the submission fails with the error:

<img width="457" alt="Screenshot 2019-04-26 at 10 10 52" src="https://user-images.githubusercontent.com/600993/56793168-9ed1f680-680b-11e9-8fcb-ee5b119a9dbe.png">

Even if when the terms of service where accepted.

This blocks users from submitting observations.

**Comment by bartaelterman** [comment]
@peterdesmet pushed a fix. Can you test?

**Comment by peterdesmet** [comment]
Updated in production: the field now appears twice:

<img width="363" alt="Screenshot 2019-04-26 at 14 25 44" src="https://user-images.githubusercontent.com/600993/56807482-44e32800-682f-11e9-8da5-955cf0a54205.png">

1. Selecting neither results in the expected warning.
2. Selecting **just one** resulted in `504 Gateway Time-out` screen, but the obs was created successfully
3. Selecting **both** resulted in a successful submission and redirection to home page.

**Comment by bartaelterman** [comment]
new fix pushed

**Comment by peterdesmet** [comment]
Now ok in production.
