### ISSUE TITLE
LC_MESSAGES directory twice

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#247]
@niconoe, what is the difference between:

- [`locale/nl/LC_MESSAGES`](https://github.com/inbo/vespa-watch/tree/master/locale/nl/LC_MESSAGES)
- [`djangoproject/locale/nl/LC_MESSAGES`](https://github.com/inbo/vespa-watch/tree/master/djangoproject/locale/nl/LC_MESSAGES)

Are both needed?

**Comment by niconoe** [comment]
Doesn't seems strange to me: one is global (to the Django project) for global things such as settings file, while the other is specific to the VespaWatch Django app.

I'll however keep it open so I'll have a second look to see if we can configure the thing to have a single one.

**Comment by peterdesmet** [comment]
👍 it looks a bit odd in root, that's all.
