### ISSUE TITLE
Allow upload of multiple photos

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#252]
Originally reported by @KarelSchoonvaere at https://github.com/inbo/vespa-watch/issues/134#issuecomment-489992220. See also #96 (dropzone) and #246 (visualize photo).

**Comment by peterdesmet** [comment]
This hasn't been requested by users yet, so would not implement this. Also nudges user to submit best photos.

**Comment by KarelSchoonvaere** [comment]
agreed.
