### ISSUE TITLE
putting location marker on the map by simple double clicking

### ISSUE THREAD

**Issue by timadriaens** [inbo/vespa-watch#254]
Hi, currently it seems only possible to move the dot cursor on the map in order to specify a location on the map. This is not handy since one has to zoom in to find the location but then the dot is no longer visible. Is it possible to ensure people can zoom to whatever level they want and then put the location marker there by clicking (once or double)? Probably the observation form also needs to explain this above the map ("_move the location marker or double click on the map to specify the location_")

**Comment by peterdesmet** [comment]
This is listed in #297.
