### ISSUE TITLE
Changing species on iNat doesn't revert back on sync

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#264]
1. https://www.inaturalist.org/observations/18426108: is a Vespa velutina ✅
2. Sync  ✅
3. Change at iNat to Vespa crabro ✅
4. Sync: updated to `Vespa crabro`, gets flag `not in vespawatch project` 👌  ✅
5. Change at iNat back to Vespa velutina ✅
6. Sync: not updated to `Vespa velutina` ✅

Are records with flags not updated?

**Comment by bartaelterman** [comment]
They should. Nice catch.

What happens to the `inaturalist_species` field?

**Comment by peterdesmet** [comment]
It's empty

**Comment by bartaelterman** [comment]
Also after step 4?

At that point, the taxon is not known so the `inaturalist_species` field should be filled in then.

**Comment by peterdesmet** [comment]
Both species are known in my local db. Only checked the field at step 4: it's currently empty.

**Comment by bartaelterman** [comment]
I'm having a hard time to reproduce this. Let's have a look together..

**Comment by peterdesmet** [comment]
This is now resolved.
