### ISSUE TITLE
automatic coordinates lookup

### ISSUE THREAD

**Issue by KarelSchoonvaere** [inbo/vespa-watch#266]
I don't know if this issue is known or relates to any previous issues. Currently 3 reports on vespawatch (not iNaturalist) have the location address but no coordinates assigned. That'll probably give issues when synchronizing with iNat as there coordinates are needed to assign a location. Correct me if I am wrong.

Were there intentions to have an automatic lookup of the coordinates that belong to a user-defined address?

**Comment by peterdesmet** [comment]
Closing issue: lat/long is now mandatory on form
