### ISSUE TITLE
vespawatch slogan

### ISSUE THREAD

**Issue by KarelSchoonvaere** [inbo/vespa-watch#269]
Currently the dutch version of the homepage has the slogan "Help de invasie van Aziatische hoornaar in kaart brengen". There was the suggestion to change this to "Help de Aziatische hoornaar in kaart te brengen".  

Similarly the English slogan misses an article before ".. Asian hornet". 

Any suggestions/idea's?

**Comment by peterdesmet** [comment]
Will look into this tomorrow.

**Comment by peterdesmet** [comment]
Will change to:

> Monitor the invasion of the Asian hornet
> Help de Aziatische hoornaar in kaart te brengen
