### ISSUE TITLE
Terms of service VS privacy policy

### ISSUE THREAD

**Issue by niconoe** [inbo/vespa-watch#272]
The "privacy policy" appears in the form, while validation messages refers to "terms of service". In Dutch, its "privacybeleid" vs "terms of service".

@peterdesmet: which label do you prefer?

**Comment by peterdesmet** [comment]
as a label: `privacypolicy`. Will be translated to `privacybeleid` and `privacy policy`.

**Comment by niconoe** [comment]
Fixed now, will create a second issue for possible issues with this form field.
