### ISSUE TITLE
Indicate to user that comment field is public

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/vespa-watch#273]
Currently, the comment field provided by the vespawatch users is used as `Description` field in the inaturalist observations. After checking a number of them, this might be not so informative. So, we should keep it out of the sync

**Comment by peterdesmet** [comment]
It is actually very useful information as context, but would be good to warn user that this is public information. @timadriaens @KarelSchoonvaere what do you think. Some examples:

https://www.inaturalist.org/observations/25556432
https://www.inaturalist.org/observations/25556452

**Comment by KarelSchoonvaere** [comment]
+ This is indeed useful information, 
- but if it is not covered by our copyright statement than we cannot make it public at iNaturalist. 
- many of the info is Dutch while currently most validators are English speaking
- information is sometimes ill-minded: "I took 5 bullets to kill the beast". That doesn't match the intention of nature observations and should be omitted.

**Comment by peterdesmet** [comment]
In my opinion it is more useful than not, but if info is to be provided to fire station for nest eradication, it will probably contain even less useful info for iNat.

**Comment by peterdesmet** [comment]
Also, @KarelSchoonvaere replying to original observer via iNat won't work: https://www.inaturalist.org/observations/25567845 they do not get a notification of any kind.

**Comment by KarelSchoonvaere** [comment]
Ok good to know.
