### ISSUE TITLE
Style vue fields on error

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#274]
With #76 fixed, the form messages look a bit better:

<img width="711" alt="Screenshot 2019-05-22 at 12 18 24" src="https://user-images.githubusercontent.com/600993/58167313-fd17bb00-7c8b-11e9-9368-8811237dbbae.png">

But the field names `terms_of_service` are still not so pretty to show to the users. It would be good if we could just indicate the error near the field in question. This works by default for Django form fields, but not for Vue fields.

- [x] Date
- [x] Location
- [ ] Terms of service

**Comment by niconoe** [comment]
Terms_of_service is a different case since it's not a Vue-based field, opening a new ticket for it.

**Comment by peterdesmet** [comment]
Fixed in #298
