### ISSUE TITLE
"privacy policy" form field cleanup

### ISSUE THREAD

**Issue by niconoe** [inbo/vespa-watch#277]
While working on #272, I also noticed:

- We should probably rename the `terms_of_service` form fields to `privacy policy` since this is what is now shown in the user.
- The `terms of service` field is defined on `IndividualForm`, `NestForm` and `NestFormUnauthenticated` but not on `IndividualFormUnauthenticated`. This seems a bit inconsistent. @bartaelterman, do you know if there's a good reason for that?

**Comment by peterdesmet** [comment]
On point two: it is now defined on the generic observation: 8dbd8bbc3bc730814518720d9aaea43ee015b009

**Comment by bartaelterman** [comment]
Implemented in 29f39a2aa899121d28ced2c275385e478a642b07

Waiting for that to be merged before closing this issue.

**Comment by peterdesmet** [comment]
This is now implemented.
