### ISSUE TITLE
Provide user accounts for each firefighters zone

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/vespa-watch#28]
An overview of the different zones is provided [here](http://www.brandweervlaanderen.be/Home/Zones.aspx). Each zone will have a user account and able to manage its own observations/management actions

**Comment by niconoe** [comment]
For modularity reasons, I will write a separate script to automatically create an account for each zone.

**Comment by niconoe** [comment]
`create_firefighters_accounts` command is now implemented. @stijnvanhoey, can you make sure it's run on initial deployment (after the other script referenced in #61).

The credentials are outputted on the console, so we'll need to capture it.

**Comment by stijnvanhoey** [comment]
Reopening for myself to make sure I add the proper instructions on deployment to capture the output!

**Comment by stijnvanhoey** [comment]
By providing the ssh command (or logging into a machine after initial setup), the command can be executed as required. Documentation is added, need to be checked in the bash instructions file.

**Comment by stijnvanhoey** [comment]
Done
