### ISSUE TITLE
Allow website access via https://www.vespawatch.be/

### ISSUE THREAD

**Issue by niconoe** [inbo/vespa-watch#282]
Website is currently accessible at https://vespawatch.be/, but https://www.vespawatch.be/ doesn't work.

Given that a large percentage of the population has no clue about "https://" nor "www" and add/remove them randomly to the URLs they encounter it could be nice if https://www.vespawatch.be/ could also work (maybe the easiest solution is to just redirect to https://vespawatch.be/).

**Comment by KarelSchoonvaere** [comment]
Good point. There are lot's of mistakes being made last weeks. Some
municipalities (gemeentes) got it all wrong on their website. I tried to
communicatie this case by case, but redirecting from www.vespawatch.be
would be great!$$

Op wo 22 mei 2019 om 14:57 schreef Nicolas Noé <notifications@github.com>:

**Comment by peterdesmet** [comment]
This is now functional, thanks @berthuygens!
