### ISSUE TITLE
French translation of interface

### ISSUE THREAD

**Issue by niconoe** [inbo/vespa-watch#287]
There has been a little bit of press coverage about Vespa-Watch on this side of the country too. Some people "complained" in comments on social media that it's only Dutch + English.

Just wanted to let you know I can do a French translation if you want, I guess it wouldn't take too long (Peter, how was it for the Dutch file?) and the infrastructure is already in place.

**Comment by peterdesmet** [comment]
Have been thinking about that too. Would be awesome if you can translate in French! It's not that much work if you're a native French speaker. Highly recommend Linguist for adding the translations.

**Comment by niconoe** [comment]
There's also the option of merging this code now (so we solve the technical parts: stale branch, migration history, ...) but disabling French for now in the language selector (so we avoid political drama).

**Comment by peterdesmet** [comment]
I'm fine merging this branch but not enabling on site.

**Comment by peterdesmet** [comment]
The French interface can now be enabled.

**Comment by niconoe** [comment]
Translation done, to be reviewed in situ and refined.

**Comment by peterdesmet** [comment]
Reviewed by whom? You?

**Comment by niconoe** [comment]
Yep, I'm planning to do it!

Would you prefer that we think of another pair of additional eyes?

**Comment by niconoe** [comment]
Done, FR version of VespaWatch is now online!
