### ISSUE TITLE
Species selector guidance

### ISSUE THREAD

**Issue by bartaelterman** [inbo/vespa-watch#29]
Display some images from the different species in the observation form. Add some text to make assist the user in selecting the right species.

**Comment by bartaelterman** [comment]
We tested it. Looks good! I added the design label for @peterdesmet because we need some styling there.
@niconoe Could you add a line of text at the end saying "If you don't know, select Insecta"?

**Comment by peterdesmet** [comment]
This functionality is no longer part of the observation form, but replaced by a page shown before #135

**Comment by peterdesmet** [comment]
Closing issue, I'll move the design labels over there.
