### ISSUE TITLE
Duplicate observations

### ISSUE THREAD

**Issue by niconoe** [inbo/vespa-watch#291]
Sometimes, duplicates observations are pushed at iNaturalist, see for example [1](https://www.inaturalist.org/observations/25673463) and [2](https://www.inaturalist.org/observations/25673451).

According to the `vespawatch_id` observation field, it seems we also have duplicates on our side. Duplicate form submission issue? How to replicate?

Also, we should document how to cleanup such cases (where to delete the duplicate observation). That's another use case for our "manual intervention checklist".

**Comment by niconoe** [comment]
@peterdesmet: we don't know exactly how that happens (difficult to replicate) but I have now pushed a supposed fix (on master).

Don't hesitate to deploy, but right before **we must manually check that there are no duplicates left in Django's database** otherwise the migration will fail (cannot add a constraint if we already have records violating it!).

Let's then evaluate how it works after a few days.

**Comment by peterdesmet** [comment]
This is has now been deployed to UAT and PRD. Submitting a duplicate observation results in 500 server error. Todo:

- Test if this stops duplicate observations
- Provide nicer error message than 500 error

**Comment by niconoe** [comment]
Hey @peterdesmet, I had a quick look at iNaturalist and I didn't see any recent duplicate. Is the bug fixed, or is it just because you delete them manually as they come?

**Comment by KarelSchoonvaere** [comment]
I deleted 1 duplicate saturday. But there are more, example the nest in
Opglabeek has been re reported this year

Op ma 17 jun. 2019 08:47 schreef Nicolas Noé <notifications@github.com>:

**Comment by peterdesmet** [comment]
Has not occurred since. Closing issue.

**Comment by KarelSchoonvaere** [comment]
@peterdesmet 
Is there a convenient way for me to mark duplicates in DJANGO?
Ideally the marked duplicate(s) are not included on the homepage map and they are not published on GBIF.

We had the case recently that duplicates were geographically separated by more than 100 m (see [1](https://www.inaturalist.org/observations/37748802) and [2](https://www.inaturalist.org/observations/37784310)). That's reason enough for not automatically marking duplicates (eg based on coordinate/date rules) is not the good way to go. There should be a supervised feature to force duplicate status of a record (allowing also "duplicate_of" field).

**Comment by peterdesmet** [comment]
Ping @niconoe
