### ISSUE TITLE
What is latitude and longitude?

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#294]
We have two reports of users being confused what Latitude/Longitude is. Maybe we should hide those fields if we have better location detection.

**Comment by KarelSchoonvaere** [comment]
what if someone takes a picture with geotag remotely and later wants to use the coordinates directly from the geotag (he doesn't know the place so can't use the map or address). 

This can happen with transect walkers or people who make a lot of nature pictures and have their own routine.

**Comment by niconoe** [comment]
Yep, I get the feeling that the different location fields and their interactions (fill this field, then we'll automatically set and save this other one...) are not crystal-clear for our visitors.

I think the interactions themselves are good, but we could/should do a better job of communicating them to the users. But I have no idea how :D

**Comment by peterdesmet** [comment]
Will be tackled in #297.
