### ISSUE TITLE
Privacy policy field improvements

### ISSUE THREAD

**Issue by niconoe** [inbo/vespa-watch#299]
On (unauthenticated) reporting forms, the "privacy policy" checkbox is not implemented using crispy forms nor Vue components, so it doesn't behave like other fields, for example:

- Value is lost if the validation fails and the form is re-displayed
- Styling (red border if invalid) is not applied 

This was initially reported in #274, but this field is not Vue-based.

**Comment by peterdesmet** [comment]
Ok to make this a regular field.

**Comment by peterdesmet** [comment]
@niconoe has this been implemented? If so, where?
