### ISSUE TITLE
Add terms of service and agree checkbox to the form

### ISSUE THREAD

**Issue by bartaelterman** [inbo/vespa-watch#30]
Define what exactly should or should not be done when the data sharing fields of an observation are `False`:  @KarelSchoonvaere can you confirm my intuition?

- [ ] `observer_approve_data_process`: we should basically ignore this observation
- [ ] `observer_approve_display`: do not show the image on the map (if we at some point display observations in a table, or if we allow users to search observations, should it also be excluded there?)
- [ ] `observer_approve_data_distribution`: do not push this observation to iNaturalist

**Comment by peterdesmet** [comment]
This choices will only make it more complex. I would prefer to put a disclaimer on the submission form stating that input data (except for personal information) will be released as open data. Could be part of the terms of service, with optional checkbox:

> - [ ] I agree with the [terms of service]().

**Comment by bartaelterman** [comment]
- Define a Terms of Service
- Add a checkbox to the form for non-registered users
- I would assume that form submission will not be possible if you don't agree to the terms of service? @peterdesmet

**Comment by peterdesmet** [comment]
On point 3: yes, not checking does not allow submission.

**Comment by bartaelterman** [comment]
The checkbox is added to the forms (see b8edb6a). Should still add a link to the terms of service.

**Comment by bartaelterman** [comment]
Done. You should add a page fragment to your db though (using the admin interface). The name of the page fragment is `terms_of_service` and this will be the content of the terms of service modal.
