### ISSUE TITLE
Create email template for notification

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#302]
Create email template for notification. The only variable is the `inaturalist url`.

- [x] Thank user
- [x] Indicate that we will remove observations that are 1) not identifiable 2) clearly have incorrect location information 3) other reasons

@KarelSchoonvaere @timadriaens I'll let you decide what else should be included in that email. The emails will be send from vespawatch@inbo.be, so users will have the possibility to reply.

**Comment by KarelSchoonvaere** [comment]
+ links to portals for reporting observations outside Flanders. But not sure how to bring this. Perhaps best to give the link to the vespawatch links page: https://vespawatch.be/about/links/

+ give a short description how they can respond in the iNaturalist survey: make account, lookup vespawatch identification page => recent observations

**Comment by KarelSchoonvaere** [comment]
Enkele aanvullingen:

- Waarnemingen zonder duidelijke of **originele** foto worden verwijderd. Op een foto van een nest is bij voorkeur ook de bijhorende wesp duidelijk zichtbaar. _(locatie zou ik weglaten, er is toch mandatory field?)_
- activiteiten: aankondigingen voor klimopblitzes worden niet gedaan via HBV maar wel via www.aculea.be. De HBV activiteiten pagina lijkt me in dit opzicht niet zinvol.

**Comment by peterdesmet** [comment]
Ik heb het template aangepast, het is nu:

> Beste {name},
> 
> Bedankt voor je melding op [Vespa-Watch](https://vespawatch.be/). Dankzij jou houden we de vinger aan de pols van de Aziatische hoornaarinvasie in Vlaanderen.
> 
> Je observatie is nu ook beschikbaar op [iNaturalist](https://www.inaturalist.org/observations/29452430), waar deze door vrijwilligers kan worden geverifieerd. Observaties met onbruikbare of niet zelf genomen foto's zullen worden verwijderd. Hou [deze pagina](https://www.inaturalist.org/observations/29452430) in de gaten om te weten welke soort je hebt gezien. Wil je deelnemen aan de identificatie en/of observaties onder je eigen naam doorsturen? Maak dan een [iNaturalist account](https://www.inaturalist.org/signup) aan.
>
> Vertel vrienden en kennissen over de Aziatische hoornaar en [lees hier](https://vespawatch.be/get-involved/) hoe je verder kan deelnemen aan dit project. Feedback? Laat het ons weten door op deze email te antwoorden.
> 
> Met vriendelijke groeten,
> 
> Het Vespa-Watch team
> 
> {small font}
> Dit is een éénmalige, automatische email die wordt verstuurd bij het melden van een observatie op Vespa-Watch. We zullen je verder geen emails sturen. Bij een geverifieerde melding van een nest van Aziatische hoornaars, kan je worden gecontacteerd door bestrijders. Zie ons [privacybeleid](https://vespawatch.be/about/privacy-policy/).
> 
> Elke melding op Vespa-Watch is publiek beschikbaar als open data, maar voor bestrijding worden enkel observaties in Vlaanderen gebruikt. Andere regio's en landen hebben vaak hun [eigen invoerportalen](https://vespawatch.be/about/links/) en bestrijdingsprogramma's voor Aziatische hoornaar.
> {/small font}

**Comment by KarelSchoonvaere** [comment]
Perfect!

**Comment by peterdesmet** [comment]
This is now implemented.

**Comment by timadriaens** [comment]
Several (mostly Brussels) observers brought to my attention that they would like a french version of the notification email ("_En Français, s'il vous plait. Merci_."). I see no objection to provide both (in the same email) and the french version can refer to the walloon portal to redirect Walloon observers. So here's a quick and dirty french version. @niconoe can you check my crude french :-) ?

Merci de faire une observation sur Vespa-Watch. Grâce à vous, nous pouvons faire le point sur l'invasion du frelon asiatique en Flandre.

Votre observation est également disponible sur iNaturalist, où elle peut être vérifiée par des bénévoles. Les observations comportant des photos inutilisables ou non prises par l'observateur seront supprimées. Gardez un œil sur cette page pour savoir quelles espèces vous avez vues. Souhaitez-vous participer à l'identification et/ou transmettre des observations sous votre propre nom ? Créez ensuite un [compte iNaturalist](https://www.inaturalist.org/signup).

Parlez du frelon aziatique à vos amis et connaissances et lisez ici comment vous pouvez participer à ce projet. Un retour d'information ? Faites-le nous savoir en répondant à ce courriel.

**Habitez-vous en Wallonie?** Pour les observations en Wallonie, nous recommandons de reporter l'information directement via [ce formulaire](http://biodiversite.wallonie.be/fr/le-frelon-asiatique.html?IDC=5999).

Bien à vous,
L'équipe de Vespa-Watch

Il s'agit d'un courriel unique et automatique envoyé lors d'une observation sur Vespa-Watch. Nous ne vous enverrons plus de courriels. Dans le cas d'un rapport vérifié d'un nid de frelons asiatiques, vous pouvez être contacté par des services de gestion. Voir notre [politique de confidentialité](https://vespawatch.be/about/privacy-policy/).

Chaque rapport sur Vespa-Watch est disponible publiquement en tant que données ouvertes, mais seules les observations en Flandre sont utilisées pour la gestion de l'espèce. D'autres régions et pays ont souvent leurs [propres portails d'encodage](https://vespawatch.be/about/links/) et programmes de contrôle.

**Comment by peterdesmet** [comment]
Nico, how difficult would it be to implement this?

**Comment by niconoe** [comment]
Is it just an update to the mail template so it includes the message in two languages? Pretty easy in that case!

Should I add that to my priority list?

**Comment by peterdesmet** [comment]
> Should I add that to my priority list?

I'll leave that up to @friedavanroy and @timadriaens

**Comment by timadriaens** [comment]
yes @niconoe , if you could do that. I don't think it is a lot of work, just adapting the mail template.

**Comment by niconoe** [comment]
Now done (I just made very minor changes to the French translation). Will ask for a quick deployment!
