### ISSUE TITLE
Genus Vespa not updated on map

### ISSUE THREAD

**Issue by KarelSchoonvaere** [inbo/vespa-watch#303]
I found this report on the map on vespawatch.be: https://www.inaturalist.org/observations/25615395
It would imply that corrected identifications from Vespa velutina to "Genus Vespa" are not yet removed from the homepage map. 

Who can check if this assumption is correct?

**Comment by peterdesmet** [comment]
No, that is not correct. The observation still had "Vespa velutina" as its title (and thus main identification) on https://www.inaturalist.org/observations/25615395. The reason for this is that all identifiers who said "Vespa" chose (green) option 1 when selecting "Vespa":

<img width="589" alt="Screenshot 2019-06-04 at 09 29 07" src="https://user-images.githubusercontent.com/600993/58859976-55e34c80-86ab-11e9-8036-315212e9a14c.png">

So no one said that there wasn't enough evidence for Vespa velutina, and as a result the more precise identification (i.e. the one at species level = Vespa velutina) stayed.

I have now added my identification for "Vespa" selecting option 2. I've also at the very bottom indicated:

<img width="647" alt="Screenshot 2019-06-04 at 09 25 19" src="https://user-images.githubusercontent.com/600993/58859938-3c420500-86ab-11e9-81cd-2f42fbf5b7d0.png">

Which means it's now a research grade observation at genus level.

The obs will disappear from the map.
