### ISSUE TITLE
Limit image file types to be uploaded

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/vespa-watch#305]
An observation without photo on iNaturalist is actually an alternative photo format uploaded to the vespawatch website, see https://www.inaturalist.org/observations/26955477

> De foto staat in raw(nef) bestand ik hoop dat je hem open krijgt

Form should limit the file types to upload.

**Comment by niconoe** [comment]
Indeed. JPEG is enough I guess? In that case I suggest to filter the file extension so it's either `jpg` or `jpeg` (case ignored).

**Comment by peterdesmet** [comment]
Yes, that seems enough.

**Comment by bartaelterman** [comment]
I'm working on the dropzone (#96) which also includes a check for file types. I'll add it there too because that will give immediate feedback (so after dragging the image instead of after submitting the form)

**Comment by peterdesmet** [comment]
Great!

**Comment by peterdesmet** [comment]
This is now implemented in the dropzone.
