### ISSUE TITLE
Legend on interactive map homepage

### ISSUE THREAD

**Issue by KarelSchoonvaere** [inbo/vespa-watch#306]
Hi,
currently we see green and orange dots on the map of Belgium. For a new user, it is not immediately clear what the color code means. Can we work towards a simple legend on top of the map?

**Comment by niconoe** [comment]
Basic version done, in `map_legend` branch.

![image](https://user-images.githubusercontent.com/386387/60020189-c91b2580-968f-11e9-9773-f2505fbaf2b7.png)

@peterdesmet : you'll probably want to improve the layout / style. It's happenning at: https://github.com/inbo/vespa-watch/blob/7fe603cf656ebfea42e58520abb20320f07589a6/static_src/js/vespawatch.js#L233

pull request will follow!

**Comment by peterdesmet** [comment]
Now live:

<img width="767" alt="Screenshot 2019-06-27 at 17 23 40" src="https://user-images.githubusercontent.com/600993/60278790-55338400-9900-11e9-90bd-4811e4e67489.png">
