### ISSUE TITLE
Delete docs folder

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#308]
@timadriaens @KarelSchoonvaere can we remove the [docs](https://github.com/inbo/vespa-watch/tree/master/docs) directory in this repo? It currently contains the old static website and (big) image files. If need be, I could copy everything to Google Drive first.

**Comment by KarelSchoonvaere** [comment]
Prefer to have it backed up at the drive. You never know.

**Comment by peterdesmet** [comment]
Done, it's in `Website (oud)` on Google Drive. Many of the images are probably duplicates of what is already available in the Drive directory `Foto's`. I'll leave it up to you/@timadriaens to clean this up.
