### ISSUE TITLE
Sync: better identification + less iNaturalist calls

### ISSUE THREAD

**Issue by niconoe** [inbo/vespa-watch#313]
As discussed recently with @pleary, we need improvements to the sync process so:

1) We properly identify ourselves in the logs by setting a custom user agent such as `VespaWatch (using Pyinaturalist)`.
2) We trigger much less queries, by requesting only records that have changed since the last sync pull process (maybe use a small overlap - 1h for example- just to be sure)

Implementation:

For 1), Pyinaturalist 0.8.0 now provides all that we need for this. Let's implement it with the global user-agent configuration.

For 2), we need after each successful pull operation to store somewhere the current datetime (maybe use something like `django-constance`) then, when available, use it to request only the recently updated records at the beginning of the `pull` code.

Notes:

We still need to make there are not more hidden API calls (for example to request eash record one by one), and it would be good to ask Patrick to check the logs after the changes, to make sure everything now looks good on his side.

**Comment by niconoe** [comment]
Better identification + saving the date of last pull is done and deployed (still need to check everything is successful). 

Making the sync lighter is still in progress.

**Comment by peterdesmet** [comment]
No longer relevant for the Jekyll generated Vespa-Watch website that has no iNaturalist sync.
