### ISSUE TITLE
Create template for map popup

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#32]
That would allow to keep that html neatly with the other templates and use `{% trans ... %}` to translate labels. The template could be loaded as an include in `index.html`, but be hidden by default. The container of that template, e.g. `div class="popup"`, could be moved to the right place (in the popup) with jQuery.

**Comment by bartaelterman** [comment]
For translations with JavaScript, there are some solutions provided by django. (See [the docs](https://docs.djangoproject.com/en/2.1/topics/i18n/translation/#internationalization-in-javascript-code))

The question was raised whether those tags will also be recognised by the `django-admin makemessages` command. Based on [this part of the documentation](https://docs.djangoproject.com/en/2.1/topics/i18n/translation/#creating-message-files-from-javascript-source-code) I would say it is possible.

Although both options will probably work, in general, if django has a solution provided, I would prefer to stick to that.
