### ISSUE TITLE
Show list of nests in Flanders on management page

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#321]
On the management page (accessible to logged in users), show a table of nests ~~in Flanders~~ that are either `inat_vv_confirmed` or `expert_vv_confirmed` (#328).

Date | Municipality | Management
--- | --- | ---
2019 July 18 10:23 | Gent | button
2019 July 17 15:14 | Roeselare | button

**Comment by bartaelterman** [comment]
I would do this based on a shapefile of Flanders. Can we get one?

**Comment by niconoe** [comment]
The good old TM_WORLD_BORDERS shapefile that you can find everywhere has different polygons for administrative regions (regions, provinces, ...).

Should I hep you with that?

**Comment by peterdesmet** [comment]
Hmm, I wouldn't filter nests on their geographic location for now, but just show all. If need be, we can use a bounding box.

**Comment by peterdesmet** [comment]
Bounding coordinates: South West [50.67, 2.53], North East [51.51, 5.94]

**Comment by bartaelterman** [comment]
Implemented. This is now an API parameter. Demonstrated on the map (although I removed the filter there before committing - it's only used on the management table):

Without filter:

![Screenshot 2019-07-31 at 11 11 57](https://user-images.githubusercontent.com/2742677/62199760-626ee300-b384-11e9-8f8a-0de5407fd424.png)

With filter:

![Screenshot 2019-07-31 at 11 11 03](https://user-images.githubusercontent.com/2742677/62199776-6c90e180-b384-11e9-8c03-1132bf58b007.png)
