### ISSUE TITLE
Create detail page for nests

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#326]
Registered users should be able to see the details of a nest. The easiest way would be to create a nest_detail page, with a similar look to the form.

**Comment by bartaelterman** [comment]
implemented in [`management` branch](https://github.com/inbo/vespa-watch/tree/management).

**Comment by peterdesmet** [comment]
I'm leaving this open until tested and merged in to `master`.

**Comment by peterdesmet** [comment]
Tested and updated. 👌
