### ISSUE TITLE
Authenticated users should also provide contact information

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#327]
On the nest and individual form, authenticated users currently don't have to provide contact information. As a result, we don't know who submitted those obs.

- [ ] Adapt form so authenticated users also have to provide all the required contact info + terms_of_service
- [ ] Since there is not difference anymore between auth and no-auth users, the model can probably be simplified: e.g. making fields mandatory.

**Comment by bartaelterman** [comment]
@peterdesmet What about accepting the privacy policy?

**Comment by peterdesmet** [comment]
Yes, would include that too, so it's the same form for everyone.
