### ISSUE TITLE
Add field "municipality" to nests

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#329]
Registered users should immediately have some idea of where a nest is located. `municipality` is probably the best way to indicate this (and more general than zone).

- [ ] Add field to nests (not really necessary for individuals)
- [ ] Reverse geocode and populate this field when creating a nest
- [ ] Populate this field for all old nests as part of migration

Note: this field replaces `zone`

**Comment by bartaelterman** [comment]
Do we use reverse geocoding? Or a geojson file with all municipalities?
Pros for using geocoding:
- probably good quality results
- will be updated without intervention from our side if municipality borders change  (although I wouldn't really bother about that argument too much)

Cons:
- Not sure how to include API calls in a database migration. I would rather set the field with a default value (`unknown`) for the migration and write a management script to replace those values.
- If you call the API on observation save, it will slow down this function. We could also add it again as hidden field to the form and fill it in when the location search is used.

I have a slight preference for storing a geo layer of municipalities in the database and join with this layer on observation save (how it used to be implemented for firestation zones).

**Comment by peterdesmet** [comment]
I like the simplicity of geocoding (no need for file, maybe even no need for PostGIS): don't we already call a geocoding API when looking for the coordinates of an observation? Would it slow down that much?

**Comment by bartaelterman** [comment]
Yes, if the user uses the `Search` button or allows location detection. (And for now he has to use one of those to get a marker on the map).
I would still prefer to keep this out of the database migration. I have the feeling that that process is too critical to put external API calls in it.

**Comment by peterdesmet** [comment]
Ok. The alternative is looking for a good file of municipalities, which might not be the easiest either. 😄

**Comment by KarelSchoonvaere** [comment]
Can this be a start? http://www.bpost2.be/zipcodes/files/zipcodes_alpha_nl.xls
