### ISSUE TITLE
Pulling iNat observations at the 'genus' rank

### ISSUE THREAD

**Issue by niconoe** [inbo/vespa-watch#33]
A few observations at iNaturalist are retrieved because they match the project criteria, they however are only identified at the genus (Vespa) level.

I currently skip them during the "pull" synchronisation. @peterdesmet, do you agree with this course of action?

**Comment by timadriaens** [comment]
There probably respresent people recording a wasp without them knowing the species name. So they count on the community for IDing. Potentially, these also contain velutina records. However, I'd keep the IDing for iNat and indeed would skip them.

**Comment by niconoe** [comment]
Good. The import process skips them, but log the issue (so if we actually read the logs, we can help with community IDs on this specimen for the next time - but we need anyway that the process is resilient to those cases!)
