### ISSUE TITLE
Flow for management actions

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#333]
- [x] Any registered user can create a management action (using the modal)
- [x] Only admin can edit management actions (in admin interface)
- [x] Only admin can delete management action (in admin interface)
- [x] Nest is considered controlled if it has an associated management action
- [x] Nests can only have 1 management action (1:1 relation)

**Comment by bartaelterman** [comment]
I'm again a bit worried that disallowing a user to edit his own management action can be annoying.

**Comment by peterdesmet** [comment]
Agreed to allow user to edit and maybe delete if not too much work to implement.

**Comment by peterdesmet** [comment]
Hide `edit/delete` for users with no rights

**Comment by bartaelterman** [comment]
Added. Full issue is now implemented.
