### ISSUE TITLE
Redirect users for authenticated pages

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#335]
- [ ] For nest detail page (included in email), redirect users to login
- [ ] After successful login, show nest detail page
- [ ] For management page (maybe included in email), redirect users to login
- [ ] After successful login, show management page

**Comment by bartaelterman** [comment]
Tested it and this seems to work out of the box. When you are not authorized to view a page, django shows the login page with this url:
`/accounts/login/?next=/management/nest/216/`

**Comment by peterdesmet** [comment]
@bartaelterman Tested for the two use case above?

**Comment by bartaelterman** [comment]
yep
