### ISSUE TITLE
Update privacy_policy regarding sharing contact info with control users

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#336]
Contact information for observations will be shared with registered control users. This should be:

- [x] Indicated in the privacy policy
- [x] Maybe added to the nest form (see also #136)

**Comment by KarelSchoonvaere** [comment]
"Jouw contactgegevens worden gedeeld met een professionele bestrijder zodat de verdelging van het nest vlot kan verlopen."

"Your contact details will be shared with a professional eradication team to ensure a quick continuation of the nest eradication."

**Comment by peterdesmet** [comment]
Please review privacy policy once more + check if notification email is sufficient.

**Comment by KarelSchoonvaere** [comment]
@peterdesmet 
- In privacy policy:
Indien u uw telefoonnummer deelt bij meldingen van nesten, kan dit gebruikt worden voor het verzamelen van bijkomende relevante informatie (toegankelijkheid, afspraak) voor het uitvoeren van nestverwijdering. 
=> this only applies for phone number. Perhaps we should extend it to "contact details" (which includes address, phone and email). Agreed?

- In email:
Dit is een éénmalige, automatische email die wordt verstuurd bij het melden van een observatie op Vespa-Watch. We zullen je verder geen emails sturen. Bij een geverifieerde melding van een nest van Aziatische hoornaars, kan je worden gecontacteerd door bestrijders. Zie ons privacybeleid.
=> OK

**Comment by peterdesmet** [comment]
Agreed regarding "contact details". @KarelSchoonvaere can you update this yourself on the privacy page (en/nl)? @niconoe can you make sure the same is mentioned when adding the French translation?

**Comment by KarelSchoonvaere** [comment]
Done in all languages;
[NL] Indien u uw **contactgegevens** deelt bij meldingen van nesten, kan dit gebruikt worden voor het verzamelen van bijkomende relevante informatie (toegankelijkheid, afspraak) voor het uitvoeren van nestverwijdering. 
[EN] If you share your **contact details** in case of reporting a nest, **this** can be used to collect additional relevant information (accessibility, appointment) for planning and performing nest removal. 
[FR] Si vous communiquez **votres coordonnées** lors de la signalisation de nids, celui-ci pourra être utilisé pour obtenir des informations pertinentes complémentaires (accessibilité, rendez-vous) ou pour procéder à l’élimination du nid.

@niconoe, is French translation adequate?

**Comment by niconoe** [comment]
Almost perfect, just a few minor edits:

[FR] Si vous communiquez vos coordonnées lors de la signalisation d'un nid, celles-ci pourront être utilisées pour obtenir des informations pertinentes complémentaires (accessibilité, rendez-vous) ou pour procéder à l’élimination du nid.

**Comment by timadriaens** [comment]
french is adapted
