### ISSUE TITLE
Remove firestations related stuff

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#337]
- [x] Users should no longer be assigned to a zone
- [x] Observations should not be assigned to a zone
- [x] Remove `manage.py` commands for creating firefighter users
- [x] Remove zones data file
- [x] Remove documentation from README

**Comment by bartaelterman** [comment]
Everything is removed on the [`management`](https://github.com/inbo/vespa-watch/tree/management) branch.
