### ISSUE TITLE
Setup SES

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#342]
Log currently states:

```
User `arn:aws:sts::532750756126:assumed-role/aws-elasticbeanstalk-ec2-role-vespawatch/i-035b8ad7d651804db' is not authorized to perform `ses:SendEmail' on resource `arn:aws:ses:eu-west-1:532750756126:identity/inbo.be'
```

**Comment by peterdesmet** [comment]
@berthuygens @rummepa is this something you could help with?

**Comment by rummepa** [comment]
yes, i need to know the from address from where you will be sending the mails and possibly to which destinations and how much mails/second...

you will need this info:
Server Name: email-smtp.eu-west-1.amazonaws.com
Port: 25, 465 or 587 -> best to use port 587
Use Transport Layer Security (TLS): Yes
Authentication: i will sent the creds through noteshred

**Comment by peterdesmet** [comment]
- from address: vespawatch@inbo.be
- destinations: many and unknown
- mails per second: will be triggered twice a day, somewhere between 2 and 20 emails in total

I'll have to look where I need to add that info you provided

mails in dev: maybe, could be useful for testing purposes, but not high priority

**Comment by rummepa** [comment]
oke, all mails from the @inbo.be domain are going to be sent, so check.
destination doesn't really matter so check
the current 'limit' is 14 mails/sec so that will be sufficient for this :)

those variables i created are environment variables, like the one's you have for ( VESPA_SU_NAME, DB_USER, etc...) is that more clear ?

**Comment by niconoe** [comment]
After some config on the Django side, I was able to send a few test messages, so I think we're good now (keeping open just so we don't forget to check with "real" emails during the sync process.

**Comment by peterdesmet** [comment]
Emails were send out yesterday, SES works. 👌
