### ISSUE TITLE
Add management buttons on nest detail page

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#349]
The management buttons currently only show up if there is **no action**. Would be to have them regardless (i.e. edit/delete if it exists).

https://github.com/inbo/vespa-watch/blob/3792fdd1b649b1b9ef43aece74d88b9df9d21d46/assets/js/vespawatch.js#L1181-L1182

**Comment by peterdesmet** [comment]
Great @bartaelterman I'm reopening this one to test and deploy.

**Comment by peterdesmet** [comment]
Doesn't seem to work.

**Comment by bartaelterman** [comment]
Did you add the management action yourself? You are only allowed to edit if you created the action.

**Comment by peterdesmet** [comment]
Yes, was logged in as superadmin

**Comment by bartaelterman** [comment]
on which environment are you testing?

**Comment by peterdesmet** [comment]
UAT, see https://uat.vespawatch.be/management/nest/27854/

**Comment by bartaelterman** [comment]
I see the button there

**Comment by bartaelterman** [comment]
JS cached?

**Comment by peterdesmet** [comment]
Indeed, caching. Good catch!
