### ISSUE TITLE
Error when editing an observation

### ISSUE THREAD

**Issue by niconoe** [inbo/vespa-watch#35]
To reproduce:

- Create an observation using the form. 
- On the map, click on the observation and select "edit"
- Change fields (I tested with the species)
- Click save

=> 
![image](https://user-images.githubusercontent.com/386387/47648995-133d1d00-db7c-11e8-9ecc-8053eca5b58e.png)

(data seems to be saved anyway)

**Comment by bartaelterman** [comment]
@niconoe I've been refactoring some stuff in those forms (to make the location picker also a Vue component). I've pushed that now. Can you test it again pls?

**Comment by niconoe** [comment]
Indeed, I'm not able to reproduce anymore! thx!
