### ISSUE TITLE
Update to Django 2.2

### ISSUE THREAD

**Issue by niconoe** [inbo/vespa-watch#356]
LTS release, with support up to April 2022.

Django itself shouldn't be too hard to upgrade, what about dependencies (PostGIS, ...)

**Comment by niconoe** [comment]
Some progress, quick update: 

The main issue seems indeed the Geospatial libraries:

- We install GDAL and its dependencies from the EPEL repository, but the packages are REALLY outdated (GDAL 1.7.3 from 2010).
- Django 2.2 requires (according to doc): GDAL 1.11 min + geos 3.4 to 3.7. Proj.4 version seems ok. 
- EPEL has no new version of GDAL, according to many Github gists, people manually compile in this case. But this is pretty long, so not suitable for Elastic Beanstalk (instances recreated very often).
- With Elastic Beanstalk, we are also stuck with Amazon linux, so not possible to convert to other distro.

Next steps:

- Check if the PostGIS version is compatible with Django 2.2 (>= 2.1 and <= 2.5)
- Check if anaconda would allow us to install recent GDAL

**Comment by niconoe** [comment]
Related discussion: https://forums.aws.amazon.com/thread.jspa?messageID=598676

**Comment by niconoe** [comment]
Another option: create a custom AMI image? : https://stackoverflow.com/questions/17326294/configuring-amazon-elastic-beanstalk-with-postgis

**Comment by niconoe** [comment]
Another idea: totally getting rid of GeoDjango, after confirming we don't need any GIS feature anymore.

But there's still the issue that PostGIS is actually used in the migration history...

**Comment by peterdesmet** [comment]
Will that affect production? Maybe comment it in requirements.txt?

**Comment by niconoe** [comment]
@peterdesmet : the purpose is to simplify the production setup, because due to some rigidity and very outdated packages on Elastic Beanstalk, it's a mess to update to Django 2.2 (and 2.1 is not supported anymore). I'd like to do some cleanup (including this update) before larger developments take place.

Most issues come from the GIS features (GeoDjango), so getting rid of them and going "basic Django" might be interesting. But it's not without any issues neither because our migration history (that we're supposed to be able to replay at anytime) depends on GeoDjango too.

Anyway, I'll find a solution soon, I was just collecting my thoughts here. 

And the lesson learned might well be to be careful with Elastic Beanstalk next time: at first It's very seducing to use all its magic to deploy an (empty) app in 30 seconds, but once this web app is not so empty anymore, you end up fighting alligators with bare hands very often, and sometimes for the simplest tasks.

**Comment by peterdesmet** [comment]
🐊🤛😂

**Comment by niconoe** [comment]
Update: I've (apparently, seems to work in UAT) been able to install recent geospatial libraries. It also seems. we currently don't use GeoDjango features anymore, it's only there so the migration history is actually executable.

Next steps:

- confirm it indeed works (try geodjango from shell)
- it relies on precompiled libraries stored on S3: move this bucket from DEV/UAT to production
- deploy to production
- continue with other updates (Django 2.2)
- alternatively, see if flattening migrations would allow to get rid of it

**Comment by niconoe** [comment]
UPDATE: did a few tests using GeoDjango features from the shell in UAT, seems to work well.

**Comment by niconoe** [comment]
Finally deployed in production!
