### ISSUE TITLE
French translation of pages

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#358]
- [x] Update the backend so French translation of pages can be provided
- [x] Copy/paste French translation of pages @KarelSchoonvaere 
- [ ] Allow user to display site in French

**Comment by niconoe** [comment]
Update: the backend is ready (I'll copy paste translations myself in the next few days).

Superusers (@peterdesmet , @KarelSchoonvaere , @timadriaens and me) already have the "French" option visible in the language selector to help reviewing this. 

This option is currently disabled non-authenticated visitors and will be enabled once we are satisfied of the result.

**Comment by niconoe** [comment]
I now have copy-pasted all page translations.

Will recheck everything in situ soon.

**Comment by niconoe** [comment]
Done, FR version of VespaWatch is now online!

**Comment by peterdesmet** [comment]
Nice 👏👏👏 🎉🎉🎉

**Comment by KarelSchoonvaere** [comment]
Great work!
