### ISSUE TITLE
MEDIA folder becomes way too large

### ISSUE THREAD

**Issue by niconoe** [inbo/vespa-watch#363]
Probably because the synchronisation process download again and again the same individual/nest pictures.

**Comment by niconoe** [comment]
Suggested solutions (A curative, 1 preventive) at : https://stackoverflow.com/questions/21941503/django-delete-unused-media-files

!! To test carefully locally then on UAT before moving to prod 
!! Making a backup of the production S3 bucket is also probably a good idea.

**Comment by niconoe** [comment]
Hmmm what's the existing `remove_orphan_images` command?

**Comment by peterdesmet** [comment]
I do not know what that command is for.

**Comment by niconoe** [comment]
- [x] Configure django-cleanup
- [x] Test django-cleanup on dev machine (ensure the basics work)
- [ ] Test django-cleanup on UAT (ensure it works with S3) (pictures manually changed, but also with the sync script)
- [ ] Deploy django-cleanup on production and do a quick check it still deletes files as expected
- [ ] Configure django-unused-media
- [ ] Test django-unused-media on UAT
- [ ] Deploy django-unused-media on production (make a backup of S3 bucket first)
- [ ] After a couple of days, delete the backup bucket
- [ ] Consider running django-unused-media during Elastic Beanstalk deployment process

**Comment by niconoe** [comment]
Update: `django-unused-media` is not compatible with S3, we'll need to find a different (custom?) solution to clean the huge current media directory in production.

**Comment by niconoe** [comment]
Update: thinking of it again, I suggest to write custom django command to replace `django-unused-media`. We can therefore make use of Django model's (to retreive the file names to keep) and its [file storage API](https://docs.djangoproject.com/en/2.2/ref/files/storage/) to abstract the file access (so it works with a local directory and a S3 bucket).

One conservative approach for this command would be to first create a new directory with only the files in use, then remove (rename?) the initial (large one) and replace it by renaming the new one.

**Comment by niconoe** [comment]
Update: it has now been run in production, all seems fine and the bucket (pictures) is now 16.8 Gb, for 9184 files. Given that there are around 4600 observations in the database, it all looks fine.

I'll close this issue now, the two management commands can be reused later if necessary (I don't think it will). 

Notes for the future:

`media_files_cleanup_step1` can always be run to check if there are unused files. And if so, we need to also run `media_files_cleanup_step2`. Thos commands should be run on the EC2 instance themselves, via SSH. It's better to configure the IO encoding (for logging), because some file names may have weird characters, making the script crashes. For example:


    $ export PYTHONIOENCODING=utf8; python manage.py media_files_cleanup_step1
