### ISSUE TITLE
Community taxon not updated in DJANGO

### ISSUE THREAD

**Issue by KarelSchoonvaere** [inbo/vespa-watch#371]
Latest observation (https://www.inaturalist.org/observations/39687905) was reported as V. crabro but corrected in iNaturalist as a bug. Meanwhile the community taxon at iNaturalist is L. occidentalis but in DJANGO the species is still V. crabro. 

Something is wrong!

**Comment by niconoe** [comment]
Finally fixed, along multiple similar issues. Thanks for your patience, I'm now taking multiple measures (#377, #376, #378, #379, #363, #366, ...) to make sure future sync issues are easier to detect and fix.

**Comment by peterdesmet** [comment]
Thanks Nico!
