### ISSUE TITLE
Large number of inaturalist calls to check/update observations one by one

### ISSUE THREAD

**Issue by niconoe** [inbo/vespa-watch#375]
This happens because we initially pull observations from iNaturalist based on the projects.

This includes only *v. velutina* observations. So for any observation that comes from VespaWatch but that is not *v. velutina* (for example misidentified *v. crabro*, that's quite common), we have to do a manual check (step 4 of the sync script: `check_all_missing()`). 

This is inconvenient; because it hits iNaturalist APIs harder than we'd like, and this makes the whole sync process super slow (1hr +, and still running), which makes debugging the sync process harder.

**Comment by KarelSchoonvaere** [comment]
Can I help?

**Comment by niconoe** [comment]
I don't think so, I wrote that more as a reminder for myself. But thanks for the proposition, I'll let you know if I need you.

**Comment by niconoe** [comment]
BTW, I strongly suspect that it's that it's that process that crashes and is interrupted before the end (due to unnoticed changes at iNaturalist responses), preventing some data updates on our sides, such as misidentified *v. velutina* observations (that were later fixed at iNaturalist). So I'm working on a fix right now.

**Comment by niconoe** [comment]
Update: the process is still long and slow (currently 1h30 in production), but at least doesn't crash anymore (it's been hardened and throttled to fix #371)

**Comment by peterdesmet** [comment]
No longer relevant for the Jekyll generated Vespa-Watch website that has no iNaturalist sync.
