### ISSUE TITLE
Make sure we are informed (mail? cloudwatch alert?) when the sync process crashes

### ISSUE THREAD

**Issue by niconoe** [inbo/vespa-watch#377]
.... it happened and stayed unnoticed for a long time, and this leads to erroneous/non updated data (such as incorrect *v. velutina* observations)

**Comment by niconoe** [comment]
One possible approach would be to create a CloudWatch alert/metric that ensure the word `done` appear at the end of each sync log (we should actually change `done` to something less common and more explicit `inaturalist sync successfully completed` for example.

**Comment by peterdesmet** [comment]
No longer relevant for the Jekyll generated Vespa-Watch website (not hosted on AWS).
