### ISSUE TITLE
Custom EC2 configuration: use Buildfile and Procfile (instead of .ebextensions)

### ISSUE THREAD

**Issue by niconoe** [inbo/vespa-watch#378]
.. At least that's what the AWS documentation suggest for Amazon Linux: https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/platforms-linux-extend.html

**Comment by peterdesmet** [comment]
No longer relevant for the Jekyll generated Vespa-Watch website (not hosted on AWS).
