### ISSUE TITLE
Location cannot be selected if browser location is turned off

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#389]
Reported by @friedavanroy (summarized by me):

> Vespawatch.be will trigger a browser pop-up that asks the user for location, but if you not allow it, there is no way to enter the location: it remains collapsed (just showing title)

@niconoe if I recall, the location form should allow manual data recording too. Can you look into this?

**Comment by niconoe** [comment]
Yep, initially we had this possibility, then at some point a JS error* was introduced that prevented that to work.

Glad you noticed it, it should be fixed now (not yet in production).

*: Note to self: data starting with "_" not exposed in the Vue object, that was not obvious but recent Vue versions now gives a proper warning, hence the library update.

**Comment by niconoe** [comment]
@friedavanroy / @peterdesmet : the fix is now deployed, please reopen this issue if you encounter any problem!
