### ISSUE TITLE
Add inaturalist link to management table

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#396]
- [ ] Add `inaturalistID` (with a link behind it) to the management table.
- [ ] I would reorder the fields too
- [ ] I would make details a link, rather than a button

Date | Municipality | iNaturalist | Details | Management
--- | --- | --- | --- | ---
Nov 10, 2020 12:30 PM | ... | [64579367](https://www.inaturalist.org/observations/64579367) | [Details](#) | Add (button)

**Comment by niconoe** [comment]
Let's also add the link to the "nest details" page (button on top-right)

**Comment by timadriaens** [comment]
I reopened this issue (unless it is dealt with elsewhere), the idea is to include `inaturalistID` in the management module

![image](https://user-images.githubusercontent.com/16116743/99515650-84cbac00-298d-11eb-903f-73d8f8ccb7c4.png)

as well as in the nest details page, good idea to provide a button.
