### ISSUE TITLE
Create 3 new URLS for CSV export of: nests / observations / management actions

### ISSUE THREAD

**Issue by niconoe** [inbo/vespa-watch#409]
Notes:

- only public data (NO CONTACT information)
- @peterdesmet mentioned: "daily update" during the meeting. I guess it can also be dynamically generated (real-time update)? That would be easier to implement.

**Comment by peterdesmet** [comment]
@niconoe if real-time is easier, then yes 😄

**Comment by niconoe** [comment]
it is, thanks!

**Comment by niconoe** [comment]
@jrhillae @timadriaens : I added a first version of this feature to the test website, can you have a look? The reports are accessible at:

- https://uat.vespawatch.be/api/csv_export/nests
- https://uat.vespawatch.be/api/csv_export/individuals
- https://uat.vespawatch.be/api/csv_export/management_actions

Thanks a lot for your patience!

**Comment by jrhillae** [comment]
@niconoe : thank you for these reports. They look already really good. I only suggest to delete some of the output columns which are not used, contain unclear info or make it harder to import the csv into excel (such as the section 'comments' which is often spread over multiple rows in excel when converting one column to multiple columns). Now there are columns in there of which I do not even know what they mean or how to interpret ;) (like "Controlled" and "expert vv confirmed").

Further, wouldn't it be more userfriendly to also only display those rows on VespaVelutina  which are validated? i.e. where species is Vespa Velutina and i_naturlist_confirmed ==TRUE?  I suppose most users will only be interested in validated observations of Vespa Velutina? Now, there are also unvalidated observations of Vespa Velutina which makes it less clear how to interpret the file.  Also species is both described in "Species" and "i Naturalist species" and one of both appears to be always NA. @timadriaens : Would do you think? Only display Vespa Velutina or also other species, and only validated data?

Besides only displaying validated data I suggest to maintain the following columns, and delete the others:

nests:   "Observation time"  "Species"  "Latitude"  "Longitude"  "iNaturalist ID" "Height"  "Size"  
individuals:   "Observation time" "Species" "Latitude"  "Longitude" "Originates in Vespawatch" "iNaturalist ID" "Behaviour" (small remark: I noticed behaviour is completely empty in this test report, but normally it should be filled in to some degree?)
nest management: all columns are ok

**Comment by timadriaens** [comment]
Indeed @jrhillae @niconoe I think we should only provide an export for **validated data of Vespa velutina**

**Comment by niconoe** [comment]
thanks @jrhillae and @timadriaens, I've updated the exports according to your remarks. I also updated the URLs, so those clearly reflect we only see a subset of the data (validated Vespa velutina). You can see the result at:

- https://uat.vespawatch.be/api/csv_export/vv_confirmed_nests/
- https://uat.vespawatch.be/api/csv_export/vv_confirmed_individuals/

**Comment by jrhillae** [comment]
@niconoe: Normally, this is already activated? How can we access the links?

Thank you.

**Comment by niconoe** [comment]
@jrhillae : the URLs are indeed already implemented on the production website:

- https://www.vespawatch.be/api/csv_export/vv_confirmed_nests/
- https://www.vespawatch.be/api/csv_export/vv_confirmed_individuals/

There are currently no clickable links displayed anywhere, so you have to copy-paste those addresses in your browser's address bar. Do you want me to add links (and where?) ?

**Comment by jrhillae** [comment]
It is good news that the links are active :). Is there also a link for the management actions?

I propose to put the links here under a subtitle "confirmed data of Vespa Velutina": https://vespawatch.be/about/links/. I think I can put them there myself in page fragments?

Thank you

**Comment by jrhillae** [comment]
The links have been added to the website
