### ISSUE TITLE
Map improvements/polishing on obs form

### ISSUE THREAD

**Issue by bartaelterman** [inbo/vespa-watch#41]
In the observation form, use one field only to search and locate the pointer. Use a separate field (the actual `location` field for the address that is fetched by reverse geocoding. The query field is not stored.
When the pointer is moved, do the reverse geocoding again to get the new address and put this in a separate field.
This field can be edited, but the pointer does not move. If the user wants that, he has to use the search field again.
When the coordinates are edited, the pointer __is__ moved

**Comment by peterdesmet** [comment]
See already:

https://github.com/inbo/vespa-watch/blob/28c48c7517d65daadd31bf6ccaa0082f183dcc78/vespawatch/static/vespawatch/js/vespawatch.js#L373-L376

I've already added an empty input field `div_id_address`. It should probably be updated to `div_id_location`,  but that one is already in use for the find position field, which I would call `div_id_position`.

**Comment by peterdesmet** [comment]
Any updates will be tackled in #297
