### ISSUE TITLE
Update privacy statement

### ISSUE THREAD

**Issue by niconoe** [inbo/vespa-watch#410]

**Comment by jrhillae** [comment]
I have a suggestion for the new privacy statement: 

https://docs.google.com/document/d/1SJQV7X2RZIwXTtrGa0oR8uTF3eUnJTvYmPaxBeZQn7E/edit?usp=sharing

Is it sufficient to cover the fact that Dominique and 2 additional persons from VBI can access the personal data on the website in the admin section?

**Comment by jrhillae** [comment]
I translated the new statement:

https://docs.google.com/document/d/1SJQV7X2RZIwXTtrGa0oR8uTF3eUnJTvYmPaxBeZQn7E/edit?usp=sharing

I am putting the new statement on the website today so that I can give Dominique access to his new account (including contact info), but any remarks are always welcome.

**Comment by niconoe** [comment]
Great, thanks a lot Jasmijn. I did some minor fixes to the French text.

**Comment by jrhillae** [comment]
@niconoe : thank you for checking the French text.

**Comment by peterdesmet** [comment]
Hi @jrhillae I have rewritten the paragraph in the Google doc to (hopefully) clarify it. Can you have a look and if ok, @niconoe can you update the French text?

**Comment by jrhillae** [comment]
@peterdesmet : The new paragraph  is more clear now. @niconoe : if you have time to update the French text I will update it on the website.

**Comment by niconoe** [comment]
Text finally updated in Google Docs!

**Comment by jrhillae** [comment]
@niconoe : thank you for your update. I have put the new version of the privacy statement on the website.
