### ISSUE TITLE
Current users of Vespa-Watch should be reviewed

### ISSUE THREAD

**Issue by niconoe** [inbo/vespa-watch#411]
By Jasmijn and Tim.

**Comment by jrhillae** [comment]
Is it ok to delete the following super users?:

stijn.vanhoey@inbo.be
frieda.vanroy@inbo.be
dries laget

I propose to maintain the account with full rights for Karel, as he is still active as a vespawatcher.

**Comment by niconoe** [comment]
Sounds good to me. @jrhillae: I suggest disabling the users rather than deleting them (they won't be able to login, but at least we keep the history and possibly related entities).
