### ISSUE TITLE
Website Not Found

### ISSUE THREAD

**Issue by jrhillae** [inbo/vespa-watch#416]
Yesterday, only one observation was reported due to problems with the website.

When clicking on a link on the homepage you get the following error:

"the requested URL was not found on this server".

Is it possible to check this?

**Comment by peterdesmet** [comment]
Thank you for reporting this! @niconoe @berthuygens any idea what is causing https://vespawatch.be/ to show “index of”?

**Comment by peterdesmet** [comment]
I see that https://www.vespawatch.be/ works, so likely a redirect issue.

**Comment by peterdesmet** [comment]
Issue resolved. Thanks @berthuygens!
