### ISSUE TITLE
Give some users access to view all data (but not the right to modify anything)

### ISSUE THREAD

**Issue by jrhillae** [inbo/vespa-watch#417]
As noted before, some users of the managers module also want access to all the data (including personal contact info - see issue on modifying privacy statement). I tested the module to create user profils and if we create a staf user and only add the following extra rights:

Can View permission
Can View Content type
Can view constance
Can view individual
Can view management action
Can view nest

![image](https://user-images.githubusercontent.com/35692395/117830713-2e706380-b274-11eb-8eb6-54c1fc3d500f.png)

Then, this user can access the admin page, but once there, he/she can only export the data of individuals, nests and nest management. Without modifying anything. (I checked this)

![image](https://user-images.githubusercontent.com/35692395/117823788-244b6680-b26e-11eb-9200-a48d421f47f8.png)

Is it ok if I modify the profile of Dominique in this way?

**Comment by peterdesmet** [comment]
Since non-bulk contact info for nest observations is already available to them, I assume this is to allow them access (in bulk) to contact info for individual observations?
