### ISSUE TITLE
how to modify direct notifications to iNaturalist?

### ISSUE THREAD

**Issue by jrhillae** [inbo/vespa-watch#419]
I came across some errors in notifications that were send to iNaturlist directly (not by VespaWatch). Apparently, I do not have the right to modify these in iNaturalist. How do we deal with these cases?

**Comment by peterdesmet** [comment]
Can you clarify? If need be, @timadriaens can share the login details for iNaturalist.

**Comment by jrhillae** [comment]
@peterdesmet : For instance  https://www.inaturalist.org/observations/16991634 and https://www.inaturalist.org/observations/16993436 are duplicates from the same nest but not posted to iNaturalist by VespaWatch. They have been posted by two personal accounts. So the login of VespaWatch is not sufficient here to delete one of both items.

**Comment by peterdesmet** [comment]
Indeed. The only solution is to mark these as duplicate in the management action.

**Comment by jrhillae** [comment]
So far, this option did not exist in the management module. But we are planning on incorporating it and then I can correct for duplicates (also in the past) @KarelSchoonvaere : Did you save duplicates manually? Or do you have an overview of duplicates?

**Comment by KarelSchoonvaere** [comment]
Duplicates are marked somewhere in one of the manually curated excel files.
I'll have a look tonight if you don't find it.

Karel

Op ma 31 mei 2021 12:37 schreef jrhillae ***@***.***>:

**Comment by jrhillae** [comment]
@KarelSchoonvaere : There is no excel called duplicates, maybe I missed it. Do you remember in which file it was?

**Comment by jrhillae** [comment]
This problem is dealt with in the new version of the management module.
