### ISSUE TITLE
change title on homepage

### ISSUE THREAD

**Issue by jrhillae** [inbo/vespa-watch#429]
Apparently, many observations from Wallonia and the Netherlands are posted on vespawatch. Therefore, Dominique suggested to rename the website to :

NL : Help de Aziatische hoornaar in kaart te brengen in Vlaanderen
FR: Suivez l'invasion du frelon asiatique en Flandre
EN: Monitor the invasion of the Asian hornet in Flanders 

Is this suggestion ok or is there a better solution that I am overlooking?

Additionally, the links to the other websites (the Netherlands and Wallonia) should be put on the homepage, to make them more visible? Or would that make it too crowded?

**Comment by niconoe** [comment]
Changing the subtitle to add "in Vlaanderen" in 3 languages seems like a good idea to me.

I'm not sure about the location of links to other websites, maybe @peterdesmet has an opinion?

**Comment by peterdesmet** [comment]
Note that adding “in Vlaanderen” in the title can have a big impact on the (mobile) layout. Please test.

I would not add the links to the other sites on the homepage. They are mentioned elsewhere. @timadriaens has final decision on this imo: he knows the intricacies between the regions.

**Comment by jrhillae** [comment]
If I test it, it looks like this. How can I check the mobile layout?

http://127.0.0.1:8000/

![Screenshot from 2021-08-17 14-21-18](https://user-images.githubusercontent.com/35692395/129724924-bedd3869-5871-4c3b-bdab-17ea0c29f01a.png)

**Comment by jrhillae** [comment]
This is how it looks when I resize the screen 

![Screenshot from 2021-08-17 14-29-30](https://user-images.githubusercontent.com/35692395/129725860-4a5dbcc1-bdea-4eda-a6c0-fe3d8de47732.png)

**Comment by niconoe** [comment]
That looks good I think, can you create a pull request for this change?
