### ISSUE TITLE
Custom User/profile model

### ISSUE THREAD

**Issue by niconoe** [inbo/vespa-watch#43]
User has a zone, and the zone has a polygon? Something else?

**Comment by peterdesmet** [comment]
User is a zone. Polygons will be provided via #46

**Comment by peterdesmet** [comment]
> so the user "has" a zone instead of "is" a zone)?

ok!

**Comment by niconoe** [comment]
Basics are implemented! 

Next step is polygon, but we're blocked until we have the confirmation that we can use PostGIS/GeoDjango (for AWS deployment).
