### ISSUE TITLE
Vespawatch website is not working

### ISSUE THREAD

**Issue by jrhillae** [inbo/vespa-watch#435]
The website link (vespawatch.be) is not working at the moment. Also the API that Nico created do not work anymore (I based an Rshiny app on it, which can not longer read in data). Is it possible to solve this issue?

Thank you.

![image](https://user-images.githubusercontent.com/35692395/135745488-f4400429-38c4-45f9-bfeb-61518a165103.png)

**Comment by timadriaens** [comment]
yes, same here... it is the same in all browsers. Heeeeeelp, urgent fix needed as it is high season for hornets...

**Comment by niconoe** [comment]
Hi all, I saw your messages and try to provide a quick fix on a Sunday. Unfortunately I don't have full access without IT support since it's a production environment, and so far I don't understand exactly what happens.

I'll keep you informed, sorry for the interruption.

**Comment by niconoe** [comment]
Apparently I was able to circumvent the problem in a very fragile way. I'll look for a sustainable solution in the next days (tuesday at the latest). Hopefully our cloud provider doesn't automatically detect an issue and recreate server instances, or we'll see the issue again.

**Comment by niconoe** [comment]
Sorry, it indeed detect my hack and restart the thing (in a failed state...) grrrrr

**Comment by KarelSchoonvaere** [comment]
If you keep refreshing it sometimes works in chrome/Android.

**Comment by niconoe** [comment]
Indeed, two servers are running: one is okay, one is not.

**Comment by niconoe** [comment]
I was not able to find a quick fix, and unfortunately will have to postpone since I'm alone at home with two little ones who don't want to nap. I'll solve that and let you know ASAP.

**Comment by jrhillae** [comment]
Hi Nico,

Thank you for trying to fix it. Maybe we can just put a message on the
facebook group of vespawatchers that the website is temporarily
unavailable? And reports can be sended to ***@***.*** instead? It is
a very rainy day, so don't mind that you can not fix it today Nico! We
would not have received a lot of reports.

Kind regards, Jasmijn

Op zo 3 okt. 2021 13:46 schreef Nicolas Noé ***@***.***>:

**Comment by niconoe** [comment]
Okay, apparently I finally have a decent fix (works on https://uat.vespawatch.be/).

I ask IT ops to urgently deploy it to the production server (I don't have the rights to perform that myself).

**Comment by niconoe** [comment]
Issue solved, sorry for the interruption.
