### ISSUE TITLE
what is the function of confirmed_by_expert?

### ISSUE THREAD

**Issue by jrhillae** [inbo/vespa-watch#438]
If this is set to 'yes', a nest is immediately added to the management module (even when not confirmed to be Vv by iNaturalist).

**Comment by niconoe** [comment]
Indeed, as we discovered during yesterday's session, a nest appear in the management module either if it's confirmed as Vespa Velutina by the iNaturalist community (that's the normal route), either if it's flagged as "validated by expert" on Vespa-Watch.

I suspect this mechanism was actually added to be able to manually make a nest appear in the management module, in case it was not possible to get the identification confirmed on iNaturalist (i.e. unusable picture in terms of species identification).

@jrhillae: would you like me to dig a bit into the past (git history, mail exchanges, ...) to confirm this theory and understand a bit more why is this mechanism there and how it works?

**Comment by jrhillae** [comment]
@niconoe : I checked this subject in old issues and it confirms what you suspect. Thank you for clarifying.
