### ISSUE TITLE
Create observation subclasses

### ISSUE THREAD

**Issue by bartaelterman** [inbo/vespa-watch#44]
Instead of using an observation type to distinguish between nests or individuals, it seems more appropriate to work with an abstract model `Observation` and two subclasses: `Nest` and `Individual`.
The reason for this is that it seems at this point that the two things (individuals and nests) have diverged far enough to justify two separate classes:

- an obervation of a nest can be flagged as a duplicate of another nest #45 
- management actions will only be added to nests
- firefighters only want to see reports about nests #40 
- individuals can be linked to a nest **not a requirement**
- certain fields only make sense on one of the two (`behaviour` makes little sense for a nest for example)

However, there will still be some logic that should apply to the two (recording the location, syncing with iNaturalist, ...) so that logic can be added to the abstract `Observation` class. Furthermore, in later stages we could create additional subclasses to serve different use cases.

**Comment by niconoe** [comment]
Technically, I think we'll have the choice between Abstract base classes (https://godjango.com/blog/django-abstract-base-class-model-inheritance/) and Multi-Table inheritance (https://godjango.com/blog/django-abstract-base-class-multi-table-inheritance/).

I don't know have an opinion yet, but it would be good to at least check the two links above so we make the most informed choice.

**Comment by peterdesmet** [comment]
1. I assume the 999 is just a migration fix that will not hamper production databases where an actual management action with id 999 might exist.
2. Having an in between page for nest vs individual is fine.

Can you submit a PR?

**Comment by bartaelterman** [comment]
Yes, the 999 is only applied to management actions that already exist when this migration is applied to a database. Will not have an impact after that.
