### ISSUE TITLE
Synchronization stopped

### ISSUE THREAD

**Issue by jrhillae** [inbo/vespa-watch#457]
Hi,

Synchronization wiht iNaturalist did not happen this evening. During the day we had more than 20 observations on the website but none were synchronized. Is it possible to solve this? It is very important for management that nests are synchronized. At the moment it is high season for nest management.

Thank you for your help,
Jasmijn

**Comment by jrhillae** [comment]
This morning synchronization was ok, for some unknown reason it did not happen yesterday evening.

**Comment by peterdesmet** [comment]
I wish all issues would resolve themselves like this 😄
