### ISSUE TITLE
modify automatic reply email

### ISSUE THREAD

**Issue by jrhillae** [inbo/vespa-watch#458]
The automatic reply email should be extended so that the following sentence is included:

'Bij melding van een nest Aziatische hoornaars wordt u gecontacteerd door het VBI om de bestrijding te regelen.'

"Lorsqu'un nid de frelons asiatiques est signalé, vous serez contacté par le VBI pour organiser le contrôle."

@timadriaens : Is this ok?

**Comment by timadriaens** [comment]
As discussed today, think you can add "Bij melding van een nest Aziatische hoornaars wordt u gecontacteerd door het VBI om de bestrijding te regelen. Voor dringende gevallen kan U het VBI rechtstreeks contacteren" (and to include a hyperlink to their address)

**Comment by PietrH** [comment]
Can this be closed?
