### ISSUE TITLE
Get shapefile with polygons of zones

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#46]

**Comment by niconoe** [comment]
It would make sense to install GeoDjango so we can easily import/store/query/edit/... the polygons in Vespa-Watch. My only concern is on the infrastructure side, since it relies on having PostGIS, a few geospatial libraries, ...

@stijnvanhoey, could you have a look at GeoDjango's documentation and confirm all that would be fine on AWS? I can also install it in a branch so you can test there directly!

**Comment by stijnvanhoey** [comment]
I would first check if we really need it. If I understand it well:
- import/store: load a feature (vector) data set; one or two of them, which one? available online as service? 
- query: for our (observation/nest) coordinates, check WITHIN operator on these polygons. Any other operators required?
- edit: ??! *are we editing raw input feature files for/within application?*

if it is actually just *points in polygons* and the polygon dataset would be a WFS service (many of which support WITHIN operator), we would not need it on our side, but would be able to call existing wfs services. 

For municipalities, [version 2019](https://geoservices.informatievlaanderen.be/overdrachtdiensten/VRBG2019/wfs?REQUEST=GetCapabilities&SERVICE=WFS) and [version 2013](https://geoservices.informatievlaanderen.be/overdrachtdiensten/VRBG2003/wfs?REQUEST=GetCapabilities&SERVICE=WFS) are both available.
I found on https://xyz.michelstuyts.be/ a firefighters xyz-tile service, but that is probably not useful for our case?

Next, does this require the database to have the postgis extension as well, or is it just using the spatial functionalities of Geos that will be used by geodjango code?

When required, this indeed requires more installation/configuration and I would first do a check with a separate branch to evaluate the impact on setup/deployment.

**Comment by niconoe** [comment]
You understand it well: it's (for the moment) just:

- polygons import (probably once)
- check point-in-polygon when adding an observation.

the big questions are indeed: 

- do we have a WFS web service we can use for this?
- do we want to rely on it (this external service could easily break our "new observation" feature.)

I think we need the PostGIS database for GeoDjango. But a third way is indeed probably possible: not using GeoDjango, but manually importing/cherry-picking the pieces (like GEOS) we need to still perform the point in polygon query locally, without relying on anybody else.

**Comment by stijnvanhoey** [comment]
I agree on the WFS-service comment. The services for municipalities should be stable enough to build on top of it, but the firefighters zone will be an issue. So, we'll implement spatial support ourselve.

Options:
1. Cherry-picking GEOS pieces. Fine in the beginnning, but what with further development/maintenance?
2. Add postgis support, which seems available out of the box with postgres RDS  from AWS, https://aws.amazon.com/rds/postgresql/
3. Other *library* providing the point-in-polygon query as a standalone package (without GEOS dependency). I don't know of any on the top of my head.

My proposal: create a branch with geodjango and a spatial query function, I'll update the deployment and test/check.

**Comment by niconoe** [comment]
Sounds great!

**Comment by niconoe** [comment]
@stijnvanhoey : there's a new GeoDjango branch! I put a few comments in README about the setup. Everything's very simple on the Django side, hope the geospatial libraries won't be too painful on your side!

**Comment by stijnvanhoey** [comment]
Seems to work fine with minor changes to the deployment setup:

![image](https://user-images.githubusercontent.com/754862/48427520-2ef21700-e769-11e8-8a9b-f8b6cc49caea.png)

**Comment by niconoe** [comment]
Yeah, brilliant!

do you think I can merge the branch into `master` so we all continue from there?

**Comment by stijnvanhoey** [comment]
See PR #59, feel free to merge

**Comment by niconoe** [comment]
Done, thanks. Let's keep the ticket open since we still need to obtain and import the zone polygons.

**Comment by peterdesmet** [comment]
Here's the shapefile with the brandweerzones for 2019 (with the fusion of the cities): [Brandweerzones_2019.zip](https://github.com/inbo/vespa-watch/files/2580365/Brandweerzones_2019.zip)

The polygon is detailed (and thus big), so before uploading the postgres I would simplify it, e.g. with https://github.com/maxogden/simplify-geojson after it's converted to a geojson.

They also offered a shapefile with zones + municipalities they include, but I don't think we need that right?

**Comment by niconoe** [comment]
I added the shapefile (+ a simplified version) to /data. Closing this ticket since work continues in #61.
