### ISSUE TITLE
synchronisation stopped

### ISSUE THREAD

**Issue by jrhillae** [inbo/vespa-watch#461]
The sychronisation of observations (nests and individuals) stopped since the 3th of November. Management actions are still performed (until December!) and dependent on the reports of the website. Is it possible to check why it stopped and solve this?

**Comment by timadriaens** [comment]
Had to happen someday... dagelijks alle observaties checken en prompt onderhouden is de boodschap. Denk dat we naar de toekomst toe ons eens moeten bezinnen over de aanpak, want als we dat niet kunnen waarmaken gaan we hier blijven tegenaan botsen.

![image](https://user-images.githubusercontent.com/16116743/200271839-803ebc00-f3b1-47ec-8668-746c9579d98d.png)

**Comment by peterdesmet** [comment]
Sync log indicates authentication failure, which is caused by the iNat account being suspended. We'll have to rethink validation and request iNat to remove remaining inappropriate images/obs.
