### ISSUE TITLE
vespa-watch: page not found

### ISSUE THREAD

**Issue by jrhillae** [inbo/vespa-watch#467]
The website is not working anymore. The mainpage is found but when clicking on any button you get an error (' Not Found The requested URL was not found on this server.'). It is possible to look into this error? 

Thank you.

**Comment by PietrH** [comment]
Is it possible the django instance is offline?

This is the raw html of the vespa-watch home page as I'm receiving it, I can navigate to it via search engines: 

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<html>
 <head>
  <title>Index of /</title>
 </head>
 <body>
<h1>Index of /</h1>
<ul></ul>
</body></html>
```

When I go to vespa-watch.be directly I can't resolve the host.

**Comment by peterdesmet** [comment]
https://vespawatch.be does resolve, sometimes you need to reload the page (multiple times). This is likely caused by the fact that one of the two instances that hosts the website is dead (according to @niconoe).

**Comment by jrhillae** [comment]
Thank you for checking this. Do we need to contact Bert to solve this?

**Comment by peterdesmet** [comment]
The URL now links to the a static website.
