### ISSUE TITLE
Activate Google Maps API

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#482]
The nest report form requires a Google Maps API key in order to _display_ the map correctly (the form is functional without it though). Currently:

<img width="757" alt="Screenshot 2023-04-04 at 11 02 39" src="https://user-images.githubusercontent.com/600993/229745393-55910e29-5b34-4879-ba9c-e830da9742f6.png">

**Comment by PietrH** [comment]
key added in 4251415a406bada75f74e2f57bc67caa1d8a3e26 didn't work, reverting

**Comment by peterdesmet** [comment]
Domain now allowed, key added again in 459e5a00d37258a8333b744ce7692f59beb29f7d.
