### ISSUE TITLE
Can't submit form, no indication 

### ISSUE THREAD

**Issue by PietrH** [inbo/vespa-watch#487]
After giving location permission #486 , and filling in the form like so: 

![image](https://user-images.githubusercontent.com/48065851/230406361-cfb1ff6c-d2b1-41ab-8259-739c42b915c8.png)

Clicking the submit button doesn't seem to do anything, I get no confirmation or indication of what field is failing validation.

**Comment by peterdesmet** [comment]
This issue occurs in Firefox (on Linux)

**Comment by PietrH** [comment]
Still occurring Firefox v111.0.1 and Chromium Version 112.0.5615.49 (Official Build) snap (64-bit)

**Comment by PietrH** [comment]
Resolved, possibly in #492. Tested in Firefox and chromium versions stated above.
