### ISSUE TITLE
make sure uploaded images have unique names

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/vespa-watch#49]
Currently, files uploaded by the user are just stored with a file name as such, woth the risk of overwriting files. We should provide unique names on the django-side.

**Comment by niconoe** [comment]
Should be good! @stijnvanhoey, can you test in real life?

**Comment by stijnvanhoey** [comment]
Tested in DEV, photo file names get unique names. 

Although, we're losing the original file-name reference (e.g. of new name is `2cddbfb0-641a-4377-9b15-067b21ae4928.jpg`). @niconoe is the link between original file-name and created hash file name somewhere in the database (just in case)? If, not I would make sure the link can be made by the name (key on S3) itself, combining hash and original name.

**Comment by niconoe** [comment]
Nope, the new file name is just generated on the fly and the link is not stored. I will update so if also fit this ("keep the link") requirement.

**Comment by niconoe** [comment]
@stijnvanhoey, can you test on AWS?

**Comment by stijnvanhoey** [comment]
tested on UAT, closing.
