### ISSUE TITLE
When location is granted on form, nothing happens

### ISSUE THREAD

**Issue by PietrH** [inbo/vespa-watch#491]
When filling in the form, the form requests the browser location:

![image](https://user-images.githubusercontent.com/48065851/231159630-2a62696e-70a9-4db0-aa7e-fc69e7241bc5.png)

When it is granted, a spinner appears together with the app, but no pin. 

![image](https://user-images.githubusercontent.com/48065851/231159887-f2207903-27a7-4810-a9db-2c195df4beca.png)

Clicking coordinates again, will re prompt location sharing, only when blocking location access can I place a pin. 

Tested in Firefox v111.0.1 on Ubuntu

**Comment by peterdesmet** [comment]
@IT-FirmBV It would be good if there was a time-out for the location service. In case the browser does not return a location before the time-out, default to the no location behaviour.

**Comment by peterdesmet** [comment]
Fixed in #492

**Comment by PietrH** [comment]
Tested in FIrefox v111.0.1, works
