### ISSUE TITLE
Translate labels defined in JS

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#51]
The JS contains text strings that are displayed to user:

https://github.com/inbo/vespa-watch/blob/28c48c7517d65daadd31bf6ccaa0082f183dcc78/vespawatch/static/vespawatch/js/vespawatch.js#L279

This strings should be translatable, but the current implentation using {% trans “Text” %} is not picked up by the Django template and thus displayed as is. We’ll need to find another solution... ideally one that can make use of the same translation file.

**Comment by bartaelterman** [comment]
I've fixed it here 9943cf8c110d8d413a6234f3e9dc3b04efacc929. That initializes the translation in JavaScript. Still on the abstract-observer branch though.
