### ISSUE TITLE
add eradicator to list

### ISSUE THREAD

**Issue by jrhillae** [inbo/vespa-watch#510]
The following eradicator wants to be added to the list of eradicators:
(@SanneVanDonink , see his email if info is missing)
Hannes Jonas wesp-hoornaar bestrijding 
[hannesjonasgcv@gmail.com](mailto:hannesjonasgcv@gmail.com)
0496272174
Gemeente, Balen Ham Dessel Retie Mol Meerhout Leopoldsburg 
Stad Geel Lommel

**Comment by PietrH** [comment]
Related to #509
