### ISSUE TITLE
voeg een kolom (maximale hoogte van bestrijding) toe aan list eradicators

### ISSUE THREAD

**Issue by jrhillae** [inbo/vespa-watch#511]
Op basis van de excel hieronder zou de maximale bestrijdingshoogte per bestrijder moeten worden toegevoegd aan het overzicht (vespawatch.be/eradicators). 

[Uploading 230704 - Lijst INBO - VBI bestrijders - Akkoord - update 230704.xlsx…]()

@SanneVanDonink : als er bij een bestrijder een bepaalde hoogte ontbreekt, deze mss navragen bij de bestrijder zodat de tabel volledig is?

**Comment by jrhillae** [comment]
related to #509

**Comment by PietrH** [comment]
I'll merge the tables, Sanne will double check if it's all correct and make sure it's all clean.
