### ISSUE TITLE
info ivm bestrijding en type nesten updaten

### ISSUE THREAD

**Issue by jrhillae** [inbo/vespa-watch#514]

**Comment by jrhillae** [comment]
Op 17 augustus (en niet vroeger, want op deze dag start hun werking) dient de volgende info van Rato vzw op de website te worden geplaatst: 

In Oost-Vlaanderen worden de gevalideerde nesten doorgestuurd naar RATO vzw. RATO zal u telefonisch contacteren binnen de 10 dagen om een afspraak te maken voor het uitvoeren van bestrijding. Indien een foto bij melding onduidelijk is, kunnen we nesten niet valideren en bezorgen aan RATO. Indien je foto bij melding onduidelijk is zal je via mail de vraag krijgen een duidelijkere foto te bezorgen. In hoogdringendheid, contacteer een private bestrijder of de brandweer op eigen kosten.

**Comment by jrhillae** [comment]
@SanneVanDonink : voeg je deze paragraaf op 17 augustus ook toe aan de template van de e-mails die feedback geven aan een melder? Suggesties om het geheel vlotter te laten klinken en beter samen te laten vallen met andere paragrafen mogen altijd maar het is al aanvaardbaar in zijn huidige vorm vind ik :).

**Comment by SanneVanDonink** [comment]
@jrhillae : bij welke soort standaardmail dient deze paragraaf toegevoegd te worden?

**Comment by SanneVanDonink** [comment]
> Op 17 augustus (en niet vroeger, want op deze dag start hun werking) dient de volgende info van Rato vzw op de website te worden geplaatst:
> 
> In Oost-Vlaanderen worden de gevalideerde nesten doorgestuurd naar RATO vzw. RATO zal u telefonisch contacteren binnen de 10 dagen om een afspraak te maken voor het uitvoeren van bestrijding. Indien een foto bij melding onduidelijk is, kunnen we nesten niet valideren en bezorgen aan RATO. Indien je foto bij melding onduidelijk is zal je via mail de vraag krijgen een duidelijkere foto te bezorgen. In hoogdringendheid, contacteer een private bestrijder of de brandweer op eigen kosten.

@peterdesmet can you add this on the website (on 'report nest' and 'FAQ'). Thanks in advance!

**Comment by peterdesmet** [comment]
@SanneVanDonink kan je even aanduiden waar je dit precies wil op:

- FAQ
- Report nest (let op, deze pagina is al tamelijk lang voor je aan het formulier komt)

**Comment by SanneVanDonink** [comment]
@peterdesmet het is me nog niet zo duidelijk hoe ik dit kan aanduiden in de tekst in GitHub

Op FAQ
- Bij de vraag: 'Voeren jullie bestrijding uit?' als aparte bullet onder West-Vlaanderen
- Bij de vraag: 'Is bestrijding gratis?' als aparte bullet tussen West-Vlaanderen en Vlaams-Brabant

Op Report nest: bij 'Is bestrijding gratis?' als aparte bullet tussen West-Vlaanderen en Vlaams-Brabant
Dit is belangrijke info om op te wijzen als er achteraf toch verwarring bleek te zijn.
