### ISSUE TITLE
Map will not load

### ISSUE THREAD

**Issue by PietrH** [inbo/vespa-watch#543]
When testing the new deployment that included the searchable map, I originally was able to load the map and noticed that it didn't have a pin, or that the location search function would not update the map. 

Then when reloading the page without cache with `Cmd + F5`, the map stopped loading:

![image](https://github.com/inbo/vespa-watch/assets/48065851/59a14c9e-557c-4d6a-aad2-2c4a64104dfe)

I've tried on:

- Firefox 117.0.1 (deb not snap),
- Chromium Version 117.0.5938.88 (Official Build, snap)
- Firefox 117.0.1 (Windows, different machine)

The map does load on https://vespawatch.itfirmdevelopment.nl/

Here, I get a prompt to share location information when I click the coordinates field, the map will load as a grey field, if I refuse the location permission, the map will load. But the search bar will still not work.

On https://vespawatch.be/en/report-nest/, I do not get prompted for location permissions, not even after resetting the permission manually to block, ask or allow, or after resetting the browser to defaults. 

In chromium I am able to get coordinates to appear in the field by clicking the grey field, in firefox, nothing happens if I click the grey field

![image](https://github.com/inbo/vespa-watch/assets/48065851/67040978-b3ea-4c77-b04b-348b19cb7e68)

I do have some errors in dev console:

![image](https://github.com/inbo/vespa-watch/assets/48065851/b3e1375c-72de-4f15-bec9-176251fbfb84)

**Comment by peterdesmet** [comment]
This issue occurred on the English page due to a missing library. Fixed in https://github.com/inbo/vespa-watch/commit/a674f22b7bfc9fb5aab29cbdd96e7f1d5508c826
