### ISSUE TITLE
Observation class still loaded in the management scripts

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/vespa-watch#56]
When testing the deployment based on the new repo structure, I received following error message:

```
import_inat_project_observations.py", line 11, in <module> from vespawatch.models import Observation, Species ImportError: cannot import name 'Observation'
```
@bartaelterman I do think this is due to the https://github.com/inbo/vespa-watch/pull/53 not updating the management script. 

Should this just be fixed on the `import_inat_project_observations.py` script?

**Comment by niconoe** [comment]
Sorry `import_inat_project_observations.py` is an outdated command that should have been deleted long ago.

Please use `sync_pull` as a replacement.

**Comment by stijnvanhoey** [comment]
ok, I'll remove the original command from https://github.com/inbo/vespa-watch/blob/c3a9a129db6d926b7ec8e7bdb5f2d656a4d066f6/.ebextensions/02_python.config#L24 

Should I still add an initial load from inaturalist as part of the build procedure and  replace the current command or should we not need it at all, as sync pull will work based on schedule?

**Comment by niconoe** [comment]
Once in production, the pull (and push) process should run frequently (launched by cron for example).

They're not finished/mature enough now, but I think running sync_pull on deployment would be great so there's some initial data!

**Comment by stijnvanhoey** [comment]
ok, I'll repoen the issue andassign myself in order to have a look on how to integrate such a push/pull action in the elastic beanstalk setup.

**Comment by niconoe** [comment]
Perfect! FYI: In the current state of affairs push is probably broken, while pull is working (basics only).

**Comment by stijnvanhoey** [comment]
sync is operational during deployment/setup, still need to provide the scheduled job.
