### ISSUE TITLE
Toevoeging werkgebied verdelger

### ISSUE THREAD

**Issue by CatoCoordinator** [inbo/vespa-watch#561]
[imkerij.torbeyns@gmail.com](mailto:imkerij.torbeyns@gmail.com)

**Comment by PietrH** [comment]
Is er hier al een gekoppelde pull request of branch van?

**Comment by CatoCoordinator** [comment]
Dag Pieter,

Ik dacht dat ik dit al had gedaan. Eerst Issue in de Online versie, dan aanpassingen doen in de Desktop, en dan Pull request en de Online versie.
De gemeentes moesten aangepast worden naar  het volgende:
Aarschot, Begijnendijk, Bekkevoort, Bertem, Boortmeerbeek, Diest, Haacht, Herent, Hoeilaart, Holsbeek, Huldenberg, Keerbergen, Kortberg, Leuven, Lubbeek, Overijse, Oud-Heverlee, Rotselaar, Scherpenheuvel-Zichem, Tervuren, Tielt-Winge, Tremelo, Tildonk, Kampenhout, Steenokkerzeel, Herselt, Westerlo, Veerle-Laakdal, Tessenderlo, Geel, Kasterlee, Herentals, Meerhout, Halen, Herk de Stad, Hasselt, Zelem, Genk en Lummen

Groetjes,

Cato

**Comment by PietrH** [comment]
Geen probleem, door aan de rechterkant bij Development een pull request (of branch) te koppelen, kan je makkelijk van de issue naar de pull request gaan, en gaat de issue automatisch toe als de pull request gemerged wordt

![image](https://github.com/inbo/vespa-watch/assets/48065851/54807d41-cf77-49ed-a031-a02d06309f45)

**Comment by CatoCoordinator** [comment]
Dag Pieter,

Bedankt voor de info. Ik heb eens gekeken naar de andere issues die ik heb gemaakt (bv. Toevoegen Gemeentes Vlaams Brabant #563), en wil ervoor zorgen dat dit een Pull Request (PR) wordt, want nu is het nog een Issue. Als ik bij Development 'Create a branch' klik, krijg ik volgend scherm: 
![image](https://github.com/inbo/vespa-watch/assets/145098932/0b5a1760-cb15-4b84-aecf-cd61f0f3d802)

Wat zou ik moeten doen om hiervan een Pull Request te maken? Gewoon 'Create branch' en dan verder klikken naar linksbovenaan 'Code' > 'Compare and Pull Reqsuest'?  Zoals we gisteren hebben gedaan in de bijscholing?

**Comment by PietrH** [comment]
Dag Cato, 

Dat klopt, een issue is een forum post voor documentatie, een branch is een werkbare kopie van de main, en een pull request is een verzoek om een branch bij de main te voegen. Dus je redenering klopt volledig! Je issue, branch en pull request zijn zo volledig automatisch aan elkaar gekoppeld. 


Bedenk wel dat je de wijzigingen die je wil maken aan de main, pas doet nadat, en enkel op, de nieuwe branch die je gemaakt hebt. 


Je kan ook eerst een pull request maken, en dan bij development, link a branch/pull request, de juiste pull request aanduiden. Dat is de manuele manier om het te doen.
