### ISSUE TITLE
Toevoegen Gemeentes Vlaams Brabant

### ISSUE THREAD

**Issue by CatoCoordinator** [inbo/vespa-watch#563]
In Vlaams-Brabant hebben de volgende gemeenten een specifieke werking: [Begijnendijk](https://www.begijnendijk.be/subsidie-voor-neutralisatie-aziatische-hoornaar), [Tremelo](https://www.tremelo.be/product/3399/subsidie-bestrijding-aziatische-hoornaar), [Keerbergen](https://www.keerbergen.be/subsidie-bestrijding-aziatische-hoornaar), [Boortmeerbeek](https://www.boortmeerbeek.be/subsidie-bestrijding-aziatische-hoornaar-2), [Leuven](https://leuven.be/aziatische-hoornaar), [Holsbeek](https://www.holsbeek.be/nieuws/detail/3269/subsidie-bestrijden-aziatische-hoornaar), [Bornem](https://www.bornem.be/product/2107/) en [Puurs-Sint-Amands](https://authenticatie.vlaanderen.be/stb/html/ssologin). Meer info vind je op de website van deze gemeenten.

**Comment by CatoCoordinator** [comment]
@jrhillae , keur je dit goed?

**Comment by jrhillae** [comment]
@CatoCoordinator : vrijdag ga ik door de openstaande github issues en ook wijzigingen van Diego aan website. hij vertaalde ook alles naar Engels. Ok om even niets meer te wijzigen tot Engelstalige pagina's ook online staan? Anders lopen deze steeds achter op de Nederlandstalige. Bedankt!
