### ISSUE TITLE
The "management" tab should be accessible only to firefighters

### ISSUE THREAD

**Issue by niconoe** [inbo/vespa-watch#62]
It's currently also accessible from an admin, with possible errors du to the absence of "zone" for admins:

![capture d ecran 2018-11-15 a 10 17 08](https://user-images.githubusercontent.com/386387/48542572-cc5f5f00-e8bf-11e8-82ba-2147819283ea.png)

**Comment by bartaelterman** [comment]
How do we define an admin? I thought we agreed that that is a user with staff-status (can log into the admin section), right?

In that case, how about:

- an admin can see the management page, but he can select a zone. Could be useful for giving support.
- a user who is not admin and has no zone cannot see this page.

**Comment by bartaelterman** [comment]
by the way @niconoe . That's a lot of tabs!

**Comment by peterdesmet** [comment]
> an admin can see the management page, but he can select a zone. Could be useful for giving support.

Great
