### ISSUE TITLE
Investigate consequences of the Individual/Nest model split on the sync process

### ISSUE THREAD

**Issue by niconoe** [inbo/vespa-watch#63]
- [ ] The vespawatch_id pushed at iNaturalist will refer to either a Nest or an Individual. We can therefore have duplicates. On retrieval (we don't do it for now, except to identify which observations come from Vespa-Watch - value is ignored), wek now which model to load thanks to `vespawatch_evidence`. Not sure yet if it's a real problem.

- [ ] Pull: What should we do if the `vespawatch_evidence` field is changed at iNaturalist (first step would be to detect the case and log the issue, but it may not be sufficient). The case will probably be quite uncommon.

**Comment by peterdesmet** [comment]
Question: the app doesn't allow an nest AND an individual with the same `vespawatch_id` right? If yes, `vespawatch_id` should be a property of the abstract obs.

**Comment by niconoe** [comment]
`vespawatch_id` doesn't exists in our database, it's only an observation field pushed at iNaturalist: in our database, there are now two tables `nest` and `individual` (they inherit from an Abstract model but the shared state only exists at code-level, not at the database one). So you can perfectly have a Nest and an Individual with the same primary key=2, since they live in different tables.

So before the refactoring there was a very simple/strong in the iNaturalist -> VespaWatch direction: you could take an observation at inaturalist, read `vespawatch_id` and immediately have the primary key of our `observations` table. Now the link is a bit more indirect since you also need to inspect `vespawatch_evidence` to know in which table you can use this id. This is the first point in my initial comment, and not really a problem in itself.

The second case (how to handle a change in vespawatch_evidence between two pull processes), will be rather rare, but more problematic. 

So I created this issue to keep the problem in mind!

**Comment by bartaelterman** [comment]
Should we maybe prefix the `vespawatch_id` that we push to iNaturalist to make it explicit?

**Comment by peterdesmet** [comment]
@bartaelterman might be a good idea: `vespawatch_id = nest:43`

**Comment by niconoe** [comment]
Yeah, that seems cleaner and is easy to implement, so I'll do! The other edge case (some of our nest suddenly becomes an individual at iNaturalist, or vice-versa) will be documented in #2 (so we don't forget to handle it and this ticket is as complete as possible)

**Comment by peterdesmet** [comment]
I consider this done.
