### ISSUE TITLE
Style form validation failure messages

### ISSUE THREAD

**Issue by bartaelterman** [inbo/vespa-watch#76]
when you submit a form with errors, the errors are displayed as a default Django errorlist:
```
<ul class="errorlist">
  <li>observation_time
    <ul class="errorlist">
      <li>This field is required.</li>
    </ul>
  </li>
</ul>
```

Which looks like:

<img width="470" alt="screen shot 2018-11-19 at 08 44 25" src="https://user-images.githubusercontent.com/2742677/48692726-603e6d00-ebd7-11e8-8754-6b0303ab11d6.png">

I think that errorlist could use some styling.

**Comment by peterdesmet** [comment]
Form errors now look like:

<img width="711" alt="Screenshot 2019-05-22 at 12 18 24" src="https://user-images.githubusercontent.com/600993/58167285-e4a7a080-7c8b-11e9-8da4-c7c848782801.png">
