### ISSUE TITLE
Capture application and sync logs

### ISSUE THREAD

**Issue by bartaelterman** [inbo/vespa-watch#81]
Option 1: Capture all output at stdout and make them available in AWS cloud logs.
If that doesn't work, we can configure a logger that logs to AWS CloudWatch with [Watchtower](https://github.com/kislyuk/watchtower).

For the sync jobs, some alerting should be added in case warnings are thrown. These warnings are usually thrown when some edge case occurs and a manual intervention is needed.
For the webapp, it's also very convenient to have the logs in the cloud.

**Comment by stijnvanhoey** [comment]
different log streams to cloudwatch are enabled:
![image](https://user-images.githubusercontent.com/754862/49816379-02341e00-fd6e-11e8-88ad-e7408154b8d7.png)

Now need further testing on how toproperly handle django stdout and eventual alarm settings

**Comment by stijnvanhoey** [comment]
In the latest setup, django logs are now collected in a separate cloudwatch topic:

![image](https://user-images.githubusercontent.com/754862/53881245-6f74e980-4013-11e9-8433-39246b66fe92.png)

With respect to alerts, we can extend this in two ways:

1. format, using the django formatter in the settings, e.g.

```
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
```
Any thoughts about the required/preferred setup?

2. create alerts on specific items occurring in the logs. @niconoe and  @bartaelterman which messages should be targeted in the logs? Anyhting with `levelname` warning, error and critical?

**Comment by stijnvanhoey** [comment]
discussed and tackled during last sprint, see faec71869ecccfbe746d2058d8d038ca42b2ae0f
