### ISSUE TITLE
Add dutch translations for the labels in the .po file

### ISSUE THREAD

**Issue by bartaelterman** [inbo/vespa-watch#82]
Follow up of #14 
When that issue is done, there will be a .po file that contains all labels that need a translation. Edit that file and add dutch translations.

**Comment by bartaelterman** [comment]
It will be created by #14

**Comment by peterdesmet** [comment]
Found them in https://github.com/inbo/vespa-watch/tree/master/locale/nl/LC_MESSAGES

Question:

- How can I update the English text (e.g. if I notice errors, like this one below). I assume in views.py:

https://github.com/inbo/vespa-watch/blob/082022a3c4bf07d52032039aac94216e1136d55e/vespawatch/views.py#L78

- Are .po files generated?

**Comment by niconoe** [comment]
I added a comment for this in #14. You're right: you change them in py/html/js files, collect them with `collectmessages` then compile the with `compilemessages`.

**Comment by niconoe** [comment]
Has anyone already added Dutch messages, compiled them and saw them in the app (just to confirm the process is generally working as expected?

**Comment by peterdesmet** [comment]
Not yet

**Comment by peterdesmet** [comment]
Tested and it works. Will only complete this work once all templates are stable for 1st launch.

**Comment by peterdesmet** [comment]
Everything has been translated.
