### ISSUE TITLE
Remove zone-selector

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#91]
@bartaelterman is it possible to make a separate component for `zone-selector`, rather than it being included in `VwManagementPage `?

https://github.com/inbo/vespa-watch/blob/06d791534b40c964522a924e0e796681607bcc2f/static_src/js/vespawatch.js#L363-L378

I would like to structure the template as follows:

> Alert box for admin users with zone select box
> 
> # title (passing zone from select box or user profile)
>
> Record an observation
> 
> Rest of the `VwManagementPage` (passing zone from select box or user profile)

**Comment by bartaelterman** [comment]
Let's check whether the parent `VwManagementPage` is really needed. Maybe the different components (the zone selector, the map and the table) can talk to each other via the Vue app.

**Comment by peterdesmet** [comment]
Decided that superuser cannot select zone: all obs will be shown. This should simplify vue components (i.e. no selector).

So management page:

- for firefighter account: their zone
- for superuser: all (no zone filter)
