### ISSUE TITLE
Slider on management page should effect table

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#92]
It would be nice if the slider on the management page effects the slider AND the table below.

**Comment by bartaelterman** [comment]
Agreed. I expected some interaction between the map and the table to be requested at some point. That's why it's useful that they are already in this single `VwManagementPage` component.
I would even add that it would be useful if clicking on a row in the table would highlight the nest on the map.

**Comment by peterdesmet** [comment]
Agreed for clicking on row => highlight on map. But as discussed in #91 would rather have zone selector as separate component.

**Comment by peterdesmet** [comment]
This is low priority: it would only show on the `Uitgevoerde opdrachten` for fire fighters (see #140). It could be useful for the homepage.

**Comment by peterdesmet** [comment]
There will be no map on the management page. Closing issue.
