### ISSUE TITLE
Use a dropzone for the file upload

### ISSUE THREAD

**Issue by bartaelterman** [inbo/vespa-watch#96]
There seem to be some vue components available for this https://github.com/vuejs/awesome-vue#file-upload

**Comment by bartaelterman** [comment]
Integration with Django is not straight forward. These components assume that there is a single url where the images should be uploaded to. However in our case, it does not exist. We are working with an inline image form in the individual/nest form. That means that all image information should be sent to the `create_individual` or `update_individual` (or `_nest`) views in a single HTTP call.
We could create a separate url for only uploading images but to which individual/nest should django attach these when the user is in the process of creating a new item?
Alternatively, we could add a file uploader to the details page of a individual/nest (so the one where you cannot edit those objects themselves) but that results in bad user experience: create observation, save it, view details, attach images.

As this issue will take more time then expected, I'll stop progress here and suggest we discuss it again.

**Comment by bartaelterman** [comment]
This looks like a workable solution:

We allow the app to create images that have no nest- or individual-id yet. We create an endpoint for POSTing those images.
The dropzone component can post the images that are uploaded to this endpoint. What we need to add is that it gets the image ids from the response and fills in those in a hidden field in the nest or individual form.
When that form is submitted, the application checks the attached image ids and when the individual or nest is created, it adds that id to the images in the database.

The downside of this approach is that you have to allow "orphan" images, so images without nest or individual id. It doesn't really hurt though, and we can have a cron job to clean them up after a day or so.

However, still parking this ticket as it's still more work then expected. Need to reprioritise.

**Comment by peterdesmet** [comment]
I've put it lower on the prio, but still in https://github.com/inbo/vespa-watch/milestone/1

**Comment by bartaelterman** [comment]
Basics implemented in the dropzone branch.
To do:
- keep the pictures even reloading the form after form validation failure (could be covered in #253 too)
- add a cleanup job to remove orphan images older then a day (already added a datetime field to the images that would be needed for this).
