### ISSUE TITLE
Define behaviour vocab

### ISSUE THREAD

**Issue by peterdesmet** [inbo/vespa-watch#98]
- [x] Add `vespawatch_behaviour` field to iNat (id=10192)
2. Sync behaviour information between that iNat field and our behaviour field
3. Populate with `hunting at beehive` for iNat obs that have tag `beehive` (for @peterdesmet, see #70)

**Comment by KarelSchoonvaere** [comment]
- other [state in comment]

**Comment by peterdesmet** [comment]
@KarelSchoonvaere the user can only select one behaviour field.

@niconoe, can you preload these in the database:

- hunting at beehive
- drinking nectar on flower
- near wood source
- near water source
- flying
- captured
- dead
- other

**Comment by niconoe** [comment]
I guess this new field will appear on the report observation form? Is it mandatory?

**Comment by bartaelterman** [comment]
Isn't this about [this field](https://github.com/inbo/vespa-watch/blob/master/vespawatch/models.py#L549)

**Comment by niconoe** [comment]
okay, I forgot it was already there. Obviously it's for individuals only.

**Comment by niconoe** [comment]
@peterdesmet : so this replaces the current values: `Fouraging`, `Hunting at hive`, `At flower`, `Other`?

**Comment by peterdesmet** [comment]
Yes
